/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import Base.DSMuonQuaHan;
import Base.QLDocGia;
import Base.QLMuon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import smartlibrarydb.MyConnection;

/**
 *
 * @author dangt
 */
public class LapPhieuThu extends javax.swing.JFrame {

    /**
     * Creates new form LapPhieuThu
     */
    public LapPhieuThu() {
        initComponents();
        setNgayLapToCurrentDate();
    }
    
    // các phương thức setter
    public void setMaPhieuThu(String MaPhieuThu) {
        tfMaPhieuThu.setText(MaPhieuThu);
    }

    public void setMaPhieu(String MaPhieu) {
        tfMaPhieu.setText(MaPhieu);
    }

    public void setNgayLap(String NgayLap) {
        tfNgayLap.setText(NgayLap);
    }

    public void setLyDo(String LyDo) {
        cbLyDo.setSelectedItem(LyDo);
    }

    public void setSoTien(String SoTien) {
        tfSoTien.setText(SoTien);
    }
    
    private boolean isUpdateMode = false; // Biến để xác định chế độ

    // Phương thức để thiết lập chế độ cập nhật
    public void setUpdateMode(boolean mode) {
        this.isUpdateMode = mode;
    }
    
    private void setNgayLapToCurrentDate() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        tfNgayLap.setText(formatter.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDocGia = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        tfMaPhieuThu = new javax.swing.JTextField();
        tfMaPhieu = new javax.swing.JTextField();
        tfNgayLap = new javax.swing.JTextField();
        tfSoTien = new javax.swing.JTextField();
        btnThongKe = new javax.swing.JButton();
        btnLapPhieuThu = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        cbLyDo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDocGia.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnDocGia.setForeground(new java.awt.Color(1, 16, 156));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 70));

        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnMuonTra.png"))); // NOI18N
        btnMuonTra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 15, 156), 2, true));
        btnMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 60));
        getContentPane().add(tfMaPhieuThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 290, 35));
        getContentPane().add(tfMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 290, 35));
        getContentPane().add(tfNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 290, 35));
        getContentPane().add(tfSoTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 290, 35));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        btnLapPhieuThu.setBackground(new java.awt.Color(15, 166, 85));
        btnLapPhieuThu.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnLapPhieuThu.setForeground(new java.awt.Color(255, 255, 255));
        btnLapPhieuThu.setText("Lưu");
        btnLapPhieuThu.setBorder(null);
        btnLapPhieuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieuThuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapPhieuThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 640, 80, 20));

        btnQuayLai.setBackground(new java.awt.Color(255, 255, 255));
        btnQuayLai.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnQuayLai.jpg"))); // NOI18N
        btnQuayLai.setBorder(null);
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, 80, 20));

        cbLyDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quá hạn", "Làm hỏng/ mất" }));
        getContentPane().add(cbLyDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 290, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/LapPhieuThuTienPhat.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearText(){
        tfMaPhieuThu.setText("");   
        tfMaPhieu.setText("");
        tfNgayLap.setText("");
        cbLyDo.setSelectedIndex(0);
        tfSoTien.setText(""); 
    }
    private void btnLapPhieuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieuThuActionPerformed
        // TODO add your handling code here:
        /*String query = "insert into PHIEUTHUTIENPHAT (MaPhieuThu, MaPhieu, NgayLap, LyDo, SoTien) values (?, ?, ?, ?, ?)";
        String MaPhieuThu = tfMaPhieuThu.getText();
        String MaPhieu = tfMaPhieu.getText();
        String NgayLapStr = tfNgayLap.getText();
        String LyDo = tfLyDo.getText();

        try {
            // Parse số tiền
            int SoTien = Integer.parseInt(tfSoTien.getText());

            // Parse ngày lập
            java.util.Date ngayLapDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgayLapStr);
            java.sql.Date NgayLap = new java.sql.Date(ngayLapDate.getTime());

            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, MaPhieuThu);
            ps.setString(2, MaPhieu);
            ps.setDate(3, NgayLap);
            ps.setString(4, LyDo);
            ps.setInt(5, SoTien);

            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Lập phiếu thu tiền phạt thành công!");

                // Reset các text field sau khi lập phiếu thành công
                tfMaPhieuThu.setText("");   
                tfMaPhieu.setText("");
                tfNgayLap.setText("");
                tfLyDo.setText("");
                tfSoTien.setText("");                        
            } else {
                JOptionPane.showMessageDialog(this, "Lập phiếu thu tiền phạt thất bại.");
            }

            ps.close();
            con.close();
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lập phiếu thu tiền phạt thất bại: Số tiền không hợp lệ.");
        } catch (ParseException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lập phiếu thu tiền phạt thất bại: " + e.getMessage());
        }*/
        String MaPhieuThu = tfMaPhieuThu.getText();
        String MaPhieu = tfMaPhieu.getText();
        String NgayLapStr = tfNgayLap.getText();
        String LyDo = (String) cbLyDo.getSelectedItem();
        String SoTienStr = tfSoTien.getText();

        if (MaPhieuThu.isEmpty() || MaPhieu.isEmpty() || NgayLapStr.isEmpty() || LyDo.isEmpty() || SoTienStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }
        
        // Đặt ngày lập là ngày hiện tại nếu là insert
        if (!isUpdateMode) {
            setNgayLapToCurrentDate();
            NgayLapStr = tfNgayLap.getText();
        }

        try {
            // Parse số tiền
            int SoTien = Integer.parseInt(SoTienStr);

            // Parse ngày lập
            java.util.Date ngayLapDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgayLapStr);
            java.sql.Date NgayLap = new java.sql.Date(ngayLapDate.getTime());

            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            int result;

            if (isUpdateMode) {
                //update
                String updateQuery = "update PHIEUTHUTIENPHAT set MaPhieu = ?, NgayLap = ?, LyDo = ?, SoTien = ? where MaPhieuThu = ?";
                ps = con.prepareStatement(updateQuery);
                ps.setString(1, MaPhieu);
                ps.setDate(2, NgayLap);
                ps.setString(3, LyDo);
                ps.setInt(4, SoTien);
                ps.setString(5, MaPhieuThu);
            } else {
                //insert
                String insertQuery = "insert into PHIEUTHUTIENPHAT (MaPhieuThu, MaPhieu, NgayLap, LyDo, SoTien) values (?, ?, ?, ?, ?)";
                ps = con.prepareStatement(insertQuery);
                ps.setString(1, MaPhieuThu);
                ps.setString(2, MaPhieu);
                ps.setDate(3, NgayLap);
                ps.setString(4, LyDo);
                ps.setInt(5, SoTien);
            }

            result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, isUpdateMode ? "Cập nhật phiếu thu tiền phạt thành công!" : "Lập phiếu thu tiền phạt thành công!");
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, isUpdateMode ? "Cập nhật phiếu thu tiền phạt thất bại." : "Lập phiếu thu tiền phạt thất bại.");
            }

            ps.close();
            con.close();
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Số tiền không hợp lệ.");
        } catch (ParseException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }        
    }//GEN-LAST:event_btnLapPhieuThuActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttt = new ThuTienPhat();
        ttt.setVisible(true);
        
        dispose();        
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraActionPerformed
        // TODO add your handling code here:
        QLMuon QLM = new QLMuon();
        QLM.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMuonTraActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);

        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LapPhieuThu().setVisible(true);
            ThuTienPhat thuTienPhat = new ThuTienPhat();
            thuTienPhat.setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnLapPhieuThu;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cbLyDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfMaPhieu;
    private javax.swing.JTextField tfMaPhieuThu;
    private javax.swing.JTextField tfNgayLap;
    private javax.swing.JTextField tfSoTien;
    // End of variables declaration//GEN-END:variables

    /*void setMaPhieuThu(String MaPhieuThu) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setMaPhieu(String MaPhieu) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setNgayLap(String NgayLap) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setLyDo(String LyDo) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setSoTien(String SoTien) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setUpdateMode(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/
}
