/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;
import static smartlibrarydb.MyConnection.getConnection;

import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import smartlibrarydb.MyConnection;
/**
 *
 * @author Admin
 */
public class LapPhieuKiemKe extends javax.swing.JFrame {
    // Khai báo ButtonGroup
    private ButtonGroup groupTinhTrang = new ButtonGroup();
    /**
     * Creates new form KiemKe
     */
    public LapPhieuKiemKe() {
        initComponents();
        // Trong hàm khởi tạo hoặc constructor
        groupTinhTrang.add(rtbBinhThuong);
        groupTinhTrang.add(rtbHuHong);
        groupTinhTrang.add(rtbMat);
        groupTinhTrang.add(rtbQuaHan);
        setCurrentDate();
    }
    private void setCurrentDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date currentDate = new java.util.Date();
        txtNgayLap.setText(sdf.format(currentDate));
    }

    public void setTblCTKK(DefaultTableModel model) {
        this.tblCTKK.setModel(model);
    }

    public void setTxtMaKK(String maPhieuKK) {
        this.txtMaKK.setText(maPhieuKK);
    }

    public void setTxtNgayLap(String ngayLap) {
        this.txtNgayLap.setText(ngayLap);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaKK = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTKK = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        rtbBinhThuong = new javax.swing.JRadioButton();
        rtbHuHong = new javax.swing.JRadioButton();
        rtbMat = new javax.swing.JRadioButton();
        rtbQuaHan = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 16, 156));
        jLabel4.setText("Ngày Lập");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 16, 156));
        jLabel3.setText("Tình trạng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        txtNgayLap.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNgayLap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 400, 30));

        btnTimKiem.setBackground(new java.awt.Color(51, 153, 0));
        btnTimKiem.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 150, 50));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 16, 156));
        jLabel7.setText("Mã Phiếu kiểm kê");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 16, 156));
        jLabel8.setText("Mã Sách");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 16, 156));
        jLabel9.setText("Số Lượng");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        txtMaKK.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMaKK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtMaKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 400, 30));

        txtMaSach.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 400, 30));

        txtSoLuong.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtSoLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 400, 30));

        tblCTKK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblCTKK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCTKK);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 570, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 16, 156));
        jLabel1.setText("Tên Sách");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        txtTenSach.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTenSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 400, 30));

        rtbBinhThuong.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rtbBinhThuong.setForeground(new java.awt.Color(1, 16, 156));
        rtbBinhThuong.setText("Bình thường");
        getContentPane().add(rtbBinhThuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        rtbHuHong.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rtbHuHong.setForeground(new java.awt.Color(1, 16, 156));
        rtbHuHong.setText("Hư hỏng");
        getContentPane().add(rtbHuHong, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        rtbMat.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rtbMat.setForeground(new java.awt.Color(1, 16, 156));
        rtbMat.setText("Mất");
        getContentPane().add(rtbMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        rtbQuaHan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rtbQuaHan.setForeground(new java.awt.Color(1, 16, 156));
        rtbQuaHan.setText("Quá hạn");
        getContentPane().add(rtbQuaHan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        btnThem.setBackground(new java.awt.Color(51, 153, 0));
        btnThem.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 150, 50));

        btnLuu.setBackground(new java.awt.Color(51, 153, 0));
        btnLuu.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 150, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 16, 156));
        jLabel5.setText("Phiếu kiểm kê");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(51, 153, 0));
        btnCapNhat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LapKiemKe.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();

        // Kiểm tra tính hợp lệ của dữ liệu.
        if (maSach.isEmpty() && tenSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách hoặc tên sách để tìm.");
            return;
        }
        String query = "";
        if (!maSach.isEmpty()) {
            // Tìm kiếm theo mã sách.
            query = "SELECT TenSach, SoLuongHienCo FROM SACH WHERE MaSach = ?";
        } else if (!tenSach.isEmpty()) {
            // Tìm kiếm theo tên sách.
            query = "SELECT MaSach, SoLuongHienCo FROM SACH WHERE TenSach = ?";
        }

        try (Connection connection = MyConnection.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(query)) {

            if (!maSach.isEmpty()) {
                preparedStatement.setString(1, maSach);
            } else if (!tenSach.isEmpty()) {
                preparedStatement.setString(1, tenSach);
            }

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                if (!maSach.isEmpty()) {
                    // Hiển thị tên sách và số lượng hiện có.
                    txtTenSach.setText(resultSet.getString("TenSach"));
                    txtSoLuong.setText(String.valueOf(resultSet.getInt("SoLuongHienCo")));
                } else if (!tenSach.isEmpty()) {
                    // Hiển thị mã sách và số lượng hiện có.
                    txtMaSach.setText(resultSet.getString("MaSach"));
                    txtSoLuong.setText(String.valueOf(resultSet.getInt("SoLuongHienCo")));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách.");
            }
        } catch (SQLException e) {
            // Nếu có lỗi xảy ra trong quá trình kết nối hoặc truy vấn cơ sở dữ liệu.
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ các trường nhập liệu
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String soLuong = txtSoLuong.getText();
        String tinhTrang = "";

        // Xác định tình trạng từ các radio button
        if (rtbBinhThuong.isSelected()) {
            tinhTrang = "Bình thường";
        } else if (rtbHuHong.isSelected()) {
            tinhTrang = "Hư hỏng";
        } else if (rtbMat.isSelected()) {
            tinhTrang = "Mất";
        } else if (rtbQuaHan.isSelected()) {
            tinhTrang = "Quá hạn";
        }

        // Kiểm tra tính hợp lệ của dữ liệu
        if (maSach.isEmpty() || tenSach.isEmpty() || soLuong.isEmpty() || tinhTrang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
            return;
        }

        // Thêm dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tblCTKK.getModel();
        model.addRow(new Object[]{maSach, tenSach, Integer.parseInt(soLuong), tinhTrang});

        // Xóa các trường nhập liệu sau khi thêm
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtSoLuong.setText("");
        groupTinhTrang.clearSelection();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String maPhieu = txtMaKK.getText();
        String ngayLap = txtNgayLap.getText();
        String maNV = "NVTK003"; // Mã nhân viên mặc định

        // Kiểm tra tính hợp lệ của dữ liệu
        if (maPhieu.isEmpty() || ngayLap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu và ngày lập.");
            return;
        }

        // Bước 1: Chèn phiếu mượn
        String insertPhieuMuon = "INSERT INTO PHIEUKIEMKE (MaPhieuKK, NgayLap, MaNV) VALUES (?, ?, ?)";
        try (Connection connection = MyConnection.getConnection();
             PreparedStatement ps = connection.prepareStatement(insertPhieuMuon)) {
            ps.setString(1, maPhieu);
            ps.setString(2, ngayLap);
            ps.setString(3, maNV);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu phiếu kiểm kê: " + e.getMessage());
            return;
        }

        // Bước 2: Chèn chi tiết phiếu kiểm kê
        String insertCTPhieuQuery = "INSERT INTO CTPHIEUKK (MaPhieuKK, MaSach, SoLuongKK, TinhTrang) VALUES (?, ?, ?, ?)";
        DefaultTableModel model = (DefaultTableModel) tblCTKK.getModel();
        boolean hasError = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String maSach = (String) model.getValueAt(i, 0);
            int soLuong = (Integer) model.getValueAt(i, 2);
            String tinhTrang = (String) model.getValueAt(i, 3);

            try (Connection connection = MyConnection.getConnection();
                 PreparedStatement psCT = connection.prepareStatement(insertCTPhieuQuery)) {
                psCT.setString(1, maPhieu);
                psCT.setString(2, maSach);
                psCT.setInt(3, soLuong);
                psCT.setString(4, tinhTrang);
                psCT.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu chi tiết phiếu kiểm kê: " + e.getMessage());
                hasError = true;
                break;
            }
        }

        if (!hasError) {
            JOptionPane.showMessageDialog(this, "Lưu phiếu kiểm kê và chi tiết kiểm kê thành công!");
            // Gọi hàm xóa dữ liệu
            clearTextFields();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        String maPhieuKK = txtMaKK.getText();
        String ngayLap = txtNgayLap.getText();
        String maNV = "NVTK003"; // Mã nhân viên mặc định

        // Kiểm tra tính hợp lệ của dữ liệu
        if (maPhieuKK.isEmpty() || ngayLap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu và ngày lập.");
            return;
        }

        // Cập nhật phiếu kiểm kê
        String updatePhieuQuery = "UPDATE PHIEUKIEMKE SET NgayLap = ?, MaNV = ? WHERE MaPhieuKK = ?";

        try (Connection connection = MyConnection.getConnection();
             PreparedStatement ps = connection.prepareStatement(updatePhieuQuery)) {
            ps.setString(1, ngayLap);
            ps.setString(2, maNV);
            ps.setString(3, maPhieuKK);

            ps.executeUpdate();

            // Cập nhật hoặc thêm chi tiết phiếu kiểm kê
            DefaultTableModel model = (DefaultTableModel) tblCTKK.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                String maSach = (String) model.getValueAt(i, 0);
                String soLuongStr = model.getValueAt(i, 2).toString(); // Lấy giá trị như String
                int soLuong = Integer.parseInt(soLuongStr); // Chuyển đổi từ String sang Integer
                String tinhTrang = (String) model.getValueAt(i, 3);

                // Kiểm tra xem bản ghi đã tồn tại chưa
                String checkQuery = "SELECT COUNT(*) FROM CTPHIEUKK WHERE MaPhieuKK = ? AND MaSach = ?";
                try (PreparedStatement psCheck = connection.prepareStatement(checkQuery)) {
                    psCheck.setString(1, maPhieuKK);
                    psCheck.setString(2, maSach);
                    ResultSet rsCheck = psCheck.executeQuery();

                    if (rsCheck.next() && rsCheck.getInt(1) > 0) {
                        // Bản ghi đã tồn tại, thực hiện cập nhật
                        String updateCTQuery = "UPDATE CTPHIEUKK SET SoLuongKK = ?, TinhTrang = ? WHERE MaPhieuKK = ? AND MaSach = ?";
                        try (PreparedStatement psUpdateCT = connection.prepareStatement(updateCTQuery)) {
                            psUpdateCT.setInt(1, soLuong);
                            psUpdateCT.setString(2, tinhTrang);
                            psUpdateCT.setString(3, maPhieuKK);
                            psUpdateCT.setString(4, maSach);
                            psUpdateCT.executeUpdate();
                        }
                    } else {
                        // Bản ghi chưa tồn tại, thực hiện thêm mới
                        String insertCTPhieuQuery = "INSERT INTO CTPHIEUKK (MaPhieuKK, MaSach, SoLuongKK, TinhTrang) VALUES (?, ?, ?, ?)";
                        try (PreparedStatement psInsertCT = connection.prepareStatement(insertCTPhieuQuery)) {
                            psInsertCT.setString(1, maPhieuKK);
                            psInsertCT.setString(2, maSach);
                            psInsertCT.setInt(3, soLuong);
                            psInsertCT.setString(4, tinhTrang);
                            psInsertCT.executeUpdate();
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "Cập nhật phiếu kiểm kê thành công!");
            clearTextFields(); // Gọi hàm để xóa dữ liệu
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật phiếu kiểm kê: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed
    private void clearTextFields(){
        txtMaKK.setText("");
        txtNgayLap.setText("");
        // Xóa dữ liệu trong bảng tblCTKK
        DefaultTableModel model = (DefaultTableModel) tblCTKK.getModel();
        model.setRowCount(0); // Xóa tất cả các dòng trong bảng
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapPhieuKiemKe().setVisible(true);
            }
        });
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JRadioButton rtbBinhThuong;
    private javax.swing.JRadioButton rtbHuHong;
    private javax.swing.JRadioButton rtbMat;
    private javax.swing.JRadioButton rtbQuaHan;
    private javax.swing.JTable tblCTKK;
    private javax.swing.JTextField txtMaKK;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
