/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import smartlibrarydb.MyConnection;

/**
 *
 * @author dangt
 */
public class LapTheDG extends javax.swing.JFrame {
    private String MaDG;
    /**
     * Creates new form LapTheDG
     */
    public LapTheDG() {
        initComponents();
        setNgayLapTheToCurrentDate();
    }
    
    //các phương thức setter
    public void setMaDG(String MaDG){
        tfMaDG.setText(MaDG);
    }
    public void setHoTenDG(String HoTen){
        tfHoTenDG.setText(HoTen);
    }
    public void setMaLoai(String MaLoai){
        cbMaLoai.setSelectedItem(MaLoai);
    }
    public void setNgaySinhDG(String NgaySinh){
        tfNgaySinhDG.setText(NgaySinh);
    }
    public void setSDTDG(String SDT){
        tfSDTDG.setText(SDT);
    }
    public void setNgayLapThe(String NgayLapThe){
        tfNgayLapThe.setText(NgayLapThe);
    }
    
    private boolean isUpdateMode = false; // Biến để xác định chế độ
    
    // Phương thức để thiết lập chế độ cập nhật
    public void setUpdateMode(boolean mode) {
        this.isUpdateMode = mode;
    }
    
    private void setNgayLapTheToCurrentDate() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        tfNgayLapThe.setText(formatter.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfMaDG = new javax.swing.JTextField();
        tfHoTenDG = new javax.swing.JTextField();
        tfNgaySinhDG = new javax.swing.JTextField();
        tfSDTDG = new javax.swing.JTextField();
        tfNgayLapThe = new javax.swing.JTextField();
        btnLapTheDG = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnQuayLaiQLDG = new javax.swing.JButton();
        cbMaLoai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfMaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaDGActionPerformed(evt);
            }
        });
        getContentPane().add(tfMaDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 300, 35));

        tfHoTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoTenDGActionPerformed(evt);
            }
        });
        getContentPane().add(tfHoTenDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 300, 35));
        getContentPane().add(tfNgaySinhDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 300, 35));
        getContentPane().add(tfSDTDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 300, 35));
        getContentPane().add(tfNgayLapThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 300, 35));

        btnLapTheDG.setBackground(new java.awt.Color(15, 166, 85));
        btnLapTheDG.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnLapTheDG.setForeground(new java.awt.Color(255, 255, 255));
        btnLapTheDG.setText("Lưu");
        btnLapTheDG.setBorder(null);
        btnLapTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapTheDGActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapTheDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 664, 70, 30));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        btnQuayLaiQLDG.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        btnQuayLaiQLDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnQuayLai.jpg"))); // NOI18N
        btnQuayLaiQLDG.setBorder(null);
        btnQuayLaiQLDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiQLDGActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLaiQLDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 664, 80, 30));

        cbMaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LDG001", "LDG002" }));
        cbMaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaLoaiActionPerformed(evt);
            }
        });
        getContentPane().add(cbMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 300, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/LapTheDocGia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfHoTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoTenDGActionPerformed

    private void clearText(){
        tfMaDG.setText("");
        tfHoTenDG.setText("");
        cbMaLoai.setSelectedIndex(0);
        tfNgaySinhDG.setText("");
        tfSDTDG.setText("");
        setNgayLapTheToCurrentDate();
    }
    
    private void btnLapTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapTheDGActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        /*String query = "insert into DOCGIA (MaDG, HoTen, NgaySinh, SDT, NgayLapThe, MaLoai) values(?, ?, ?, ?, ?, ?)";
        String MaDG = tfMaDG.getText();
        String HoTen = tfHoTenDG.getText();
        //String MaLoai = tfMaLoai.getText();
        String MaLoai = cbMaLoai.getSelectedItem().toString();
        String NgaySinhStr = tfNgaySinhDG.getText();
        String SDT = tfSDTDG.getText();
        String NgayLapTheStr = tfNgayLapThe.getText();

        try {
            // Parse ngày sinh
            java.util.Date ngaySinhDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgaySinhStr);
            java.sql.Date NgaySinh = new java.sql.Date(ngaySinhDate.getTime());

            // Parse ngày lập thẻ
            java.util.Date ngayLapTheDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgayLapTheStr);
            java.sql.Date NgayLapThe = new java.sql.Date(ngayLapTheDate.getTime());

            Connection con = MyConnection.geConnection();
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, MaDG);
            ps.setString(2, HoTen);
            ps.setDate(3, NgaySinh);
            ps.setString(4, SDT);
            ps.setDate(5, NgayLapThe);
            ps.setString(6, MaLoai);

            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Lập thẻ độc giả thành công!");
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Lập thẻ độc giả thất bại.");
            }

            ps.close();
            con.close();
        } catch (ParseException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lập thẻ độc giả thất bại: " + e.getMessage());
        }*/
        
        String MaDG = tfMaDG.getText();
        String HoTen = tfHoTenDG.getText();
        String MaLoai = cbMaLoai.getSelectedItem().toString();
        String NgaySinhStr = tfNgaySinhDG.getText();
        String SDT = tfSDTDG.getText();
        String NgayLapTheStr = tfNgayLapThe.getText();

        if (MaDG.isEmpty() || HoTen.isEmpty() || NgaySinhStr.isEmpty() || SDT.isEmpty() || NgayLapTheStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        // Kiểm tra SDT có đúng 10 chữ số
        if (!SDT.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải có đúng 10 chữ số!");
            return;
        }

        // Đặt ngày lập thẻ là ngày hiện tại nếu là insert
        if (!isUpdateMode) {
            setNgayLapTheToCurrentDate();
            NgayLapTheStr = tfNgayLapThe.getText();
        }
        
        try {
            java.util.Date ngaySinhDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgaySinhStr);
            java.sql.Date NgaySinh = new java.sql.Date(ngaySinhDate.getTime());
            java.util.Date ngayLapTheDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgayLapTheStr);
            java.sql.Date NgayLapThe = new java.sql.Date(ngayLapTheDate.getTime());
            
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            int result;

            if (isUpdateMode) {
                //update
                String updateQuery = "update DOCGIA set HoTen = ?, NgaySinh = ?, SDT = ?, NgayLapThe = ?, MaLoai = ? where MaDG = ?";
                ps = con.prepareStatement(updateQuery);
                ps.setString(1, HoTen);
                ps.setDate(2, NgaySinh);
                ps.setString(3, SDT);
                ps.setDate(4, NgayLapThe);
                ps.setString(5, MaLoai);
                ps.setString(6, MaDG);
            } else {
                //insert
                String insertQuery = "insert into DOCGIA (MaDG, HoTen, NgaySinh, SDT, NgayLapThe, MaLoai) values (?, ?, ?, ?, ?, ?)";
                ps = con.prepareStatement(insertQuery);
                ps.setString(1, MaDG);
                ps.setString(2, HoTen);
                ps.setDate(3, NgaySinh);
                ps.setString(4, SDT);
                ps.setDate(5, NgayLapThe);
                ps.setString(6, MaLoai);
            }

            result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, isUpdateMode ? "Cập nhật thông tin độc giả thành công!" : "Lập thẻ độc giả thành công!");
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, isUpdateMode ? "Cập nhật thông tin độc giả thất bại." : "Lập thẻ độc giả thất bại.");
            }

            ps.close();
            con.close();
        } catch (ParseException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, (isUpdateMode ? "Cập nhật thông tin độc giả thất bại: " : "Lập thẻ độc giả thất bại: ") + e.getMessage());
        }
    }//GEN-LAST:event_btnLapTheDGActionPerformed

    private void btnQuayLaiQLDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiQLDGActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.show(); //hien thi o day
        
        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnQuayLaiQLDGActionPerformed

    private void tfMaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaDGActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfMaDGActionPerformed

    private void cbMaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaLoaiActionPerformed
        // TODO add your handling code here:
        String selectedValue = cbMaLoai.getSelectedItem().toString();
    }//GEN-LAST:event_cbMaLoaiActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapTheDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapTheDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapTheDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapTheDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapTheDG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapTheDG;
    private javax.swing.JButton btnQuayLaiQLDG;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cbMaLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfHoTenDG;
    private javax.swing.JTextField tfMaDG;
    private javax.swing.JTextField tfNgayLapThe;
    private javax.swing.JTextField tfNgaySinhDG;
    private javax.swing.JTextField tfSDTDG;
    // End of variables declaration//GEN-END:variables
}
