/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import smartlibrarydb.MyConnection;
/**
 *
 * @author ADMIN
 */
public class Login extends javax.swing.JFrame {
    MyConnection con = new MyConnection();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setBackground(new java.awt.Color(217, 217, 217));
        txtUserName.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        txtUserName.setBorder(null);
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 480, 50));

        txtPass.setBackground(new java.awt.Color(217, 217, 217));
        txtPass.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        txtPass.setBorder(null);
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 480, 50));

        btnlogin.setBackground(new java.awt.Color(217, 217, 217));
        btnlogin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(1, 16, 156));
        btnlogin.setText("LOGIN");
        btnlogin.setBorder(null);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, 480, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Login.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        
        String userName = txtUserName.getText().trim();
        String password = new String(txtPass.getPassword());
        //Kiểm tra rỗng
        if (userName.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu.");
            return;
        }
        // Thực hiện xác thực người dùng và lấy mã bộ phận từ cơ sở dữ liệu
        String maBoPhan = ""; // Biến lưu trữ mã bộ phận
        MyConnection con = new MyConnection();
        ResultSet rs;
        String query = "SELECT MaBP FROM NHANVIEN WHERE MaNV = ? AND Convert(varchar(100), DECRYPTBYPASSPHRASE(?,MatKhau))=?";
        try{
            PreparedStatement ps = con.getConnection().prepareStatement(query);
            ps.setString(1, userName); // Sử dụng tên đăng nhập làm tham số 1
            ps.setString(2, userName);
            ps.setString(3, password); // Sử dụng mật khẩu làm tham số 
            rs = ps.executeQuery();
            if (rs.next()) {
                maBoPhan = rs.getString("MaBP");
                // Sau khi có mã bộ phận, xác định và mở giao diện phù hợp
                if ("BPNVTT".equals(maBoPhan.trim())) {
                    Main_ThuThu mainThuThu = new Main_ThuThu();
                    mainThuThu.setVisible(true);
                } else if ("BPNVTK".equals(maBoPhan.trim())) {
                    Main_ThuKho mainThuKho = new Main_ThuKho();
                    mainThuKho.setVisible(true);
                } else if ("BPNVGD".equals(maBoPhan.trim())) {
                    Main_GiamDoc mainGiamDoc = new Main_GiamDoc();
                    mainGiamDoc.setVisible(true);
            } 
            else {
                JOptionPane.showMessageDialog(this, "Không có quyền truy cập cho mã bộ phận này.");
            }
            // Đóng cửa sổ đăng nhập
            this.dispose();
            } 
            else {
                JOptionPane.showMessageDialog(this, "Thông tin đăng nhập không chính xác.");
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Lỗi khi thực hiện đăng nhập: " + ex.getMessage());
        }
        
        /*
        String userName = txtUserName.getText().trim();
        String password = new String(txtPass.getPassword());

        if (userName.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu.");
            return;
        }

        String maBoPhan = ""; // Biến lưu trữ mã bộ phận

        try (
             PreparedStatement ps = con.geConnection().prepareStatement(
                     "SELECT MaBP FROM NHANVIEN WHERE MaNV = ? AND Convert(varchar(100), DECRYPTBYPASSPHRASE(?,MatKhau))=?"
             )
        ) {
            ps.setString(1, userName);
            ps.setString(2, userName);
            ps.setString(3, password);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    maBoPhan = rs.getString("MaBP");
                    System.out.println("Mã bộ phận từ cơ sở dữ liệu: " + maBoPhan);
                    // Sau khi có mã bộ phận, xác định và mở giao diện phù hợp
                    if ("BPNVTT".equals(maBoPhan.trim())) {
                    Main_ThuThu mainThuThu = new Main_ThuThu();
                    mainThuThu.setVisible(true);
                    } else if ("BPNVTK".equals(maBoPhan.trim())) {
                    Main_ThuKho mainThuKho = new Main_ThuKho();
                    mainThuKho.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Không có quyền truy cập cho mã bộ phận này.");
                    }
                    // Đóng cửa sổ đăng nhập
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thông tin đăng nhập không chính xác.");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thực hiện đăng nhập: " + ex.getMessage());
        }
        */
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
