/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

/**
 *
 * @author Ngoc Han
 */
public class Main_ThuKho extends javax.swing.JFrame {

    /**
     * Creates new form Main_ThuKho
     */
    public Main_ThuKho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLSach = new javax.swing.JButton();
        btnKiemKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnQLSach.png"))); // NOI18N
        btnQLSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 60));

        btnKiemKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnKiemKe.png"))); // NOI18N
        btnKiemKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnKiemKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnKiemKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main_ThuKho.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSachActionPerformed
        // TODO add your handling code here:
        QuanLySach newPage = new QuanLySach();
        newPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLSachActionPerformed

    private void btnKiemKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemKeActionPerformed
        // TODO add your handling code here:
        QLKiemKe qLKiemKe = new QLKiemKe();
        qLKiemKe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKiemKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_ThuKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_ThuKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_ThuKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_ThuKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_ThuKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiemKe;
    private javax.swing.JButton btnQLSach;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
