/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.awt.Color;
import javax.swing.BorderFactory;
/**
 *
 * @author ADMIN
 */
public class Main_ThuThu extends javax.swing.JFrame {

    /**
     * Creates new form Main_ThuThu
     */
    public Main_ThuThu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMuonTra = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        btnThuTienPhat = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnMuonTra.png"))); // NOI18N
        btnMuonTra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 15, 156), 2, true));
        btnMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 60));

        btnDocGia.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnDocGia.setForeground(new java.awt.Color(1, 16, 156));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 70));

        btnThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThuTienPhat.png"))); // NOI18N
        btnThuTienPhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 65));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Main_ThuThu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);
        
        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienPhatActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttp = new ThuTienPhat();
        ttp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThuTienPhatActionPerformed

    private void btnMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraActionPerformed
        // TODO add your handling code here:
        QLMuon QLM = new QLMuon();
        QLM.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMuonTraActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_ThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_ThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_ThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_ThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_ThuThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThuTienPhat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
