/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Image;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.Barcode128;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
/**
 *
 * @author dangt
 */
public class QLDocGia extends javax.swing.JFrame {
    /**
     * Creates new form QLDocGia
     */
    private DefaultTableModel tableModel;

    public QLDocGia() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        //String query = "select * from DOCGIA";
        String query = "select DOCGIA.MaDG, DOCGIA.HoTen, LOAIDOCGIA.TenLoai, DOCGIA.NgaySinh, DOCGIA.SDT, DOCGIA.NgayLapThe " +
                       "from DOCGIA " + "join LOAIDOCGIA on DOCGIA.MaLoai = LOAIDOCGIA.MaLoai";        
        ResultSet rs = MyConnection.executeQuery(query);
        
        if (rs == null) {
            // Xử lý khi không lấy được dữ liệu
            return;
        }
        
        try {
            tableModel = (DefaultTableModel) tblDSDocGia.getModel();
            tableModel.setRowCount(0); // Xóa các hàng cũ

            while (rs.next()) {
                String MaDG = rs.getString("MaDG");
                String HoTen = rs.getString("HoTen");
                //String MaLoai = rs.getString("MaLoai");
                String TenLoai = rs.getString("TenLoai");
                String NgaySinh = rs.getString("NgaySinh");
                String SDT = rs.getString("SDT");
                String NgayLapThe = rs.getString("NgayLapThe");
                
                // Thêm dòng mới vào JTable
                tableModel.addRow(new Object[]{MaDG, HoTen, TenLoai, NgaySinh, SDT, NgayLapThe});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThuTienPhat = new javax.swing.JButton();
        btnLapTheDG = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnPrintCard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSDocGia = new javax.swing.JTable();
        btnSuaDG = new javax.swing.JButton();
        btnXoaDG = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThuTienPhat.png"))); // NOI18N
        btnThuTienPhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 220, 70));

        btnLapTheDG.setBackground(new java.awt.Color(15, 166, 85));
        btnLapTheDG.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnLapTheDG.setForeground(new java.awt.Color(255, 255, 255));
        btnLapTheDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnLapTheDG.jpg"))); // NOI18N
        btnLapTheDG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 166, 85)));
        btnLapTheDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapTheDGActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapTheDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 160, 30));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        btnPrintCard.setBackground(new java.awt.Color(255, 255, 255));
        btnPrintCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnPDF.jpg"))); // NOI18N
        btnPrintCard.setBorder(null);
        btnPrintCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCardActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrintCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 100, -1, -1));

        tblDSDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Họ và tên", "Loại độc giả", "Ngày sinh", "SDT", "Ngày lập thẻ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDSDocGia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 1170, 480));

        btnSuaDG.setBackground(new java.awt.Color(15, 166, 85));
        btnSuaDG.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnSuaDG.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaDG.setText("Chỉnh sửa");
        btnSuaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDGActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, 120, 40));

        btnXoaDG.setBackground(new java.awt.Color(255, 0, 0));
        btnXoaDG.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnXoaDG.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaDG.setText("Xoá");
        btnXoaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDGActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 120, 40));

        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnMuonTra.png"))); // NOI18N
        btnMuonTra.setBorder(null);
        btnMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/QLDocGia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapTheDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapTheDGActionPerformed
        // TODO add your handling code here:
        //chuyen trang LapTheDocGia
        LapTheDG ltdg = new LapTheDG();
        ltdg.setVisible(true);
        
        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnLapTheDGActionPerformed

    private void btnThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienPhatActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttp = new ThuTienPhat();
        ttp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThuTienPhatActionPerformed

    private void btnMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraActionPerformed
        // TODO add your handling code here:
        QLMuonTra qlmuontra = new QLMuonTra();
        qlmuontra.setVisible(true);
        dispose();     
    }//GEN-LAST:event_btnMuonTraActionPerformed

    private void btnSuaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDGActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDSDocGia.getSelectedRow();
        if (selectedRow != -1) { // Kiểm tra nếu có dòng nào được chọn
            // Lấy thông tin từ bảng
            String MaDG = tblDSDocGia.getValueAt(selectedRow, 0).toString();
            String HoTen = tblDSDocGia.getValueAt(selectedRow, 1).toString();
            String MaLoai = tblDSDocGia.getValueAt(selectedRow, 2).toString();
            String NgaySinh = tblDSDocGia.getValueAt(selectedRow, 3).toString();
            String SDT = tblDSDocGia.getValueAt(selectedRow, 4).toString();
            String NgayLapThe = tblDSDocGia.getValueAt(selectedRow, 5).toString();
            // Chuyển hướng sang LapTheDG để sửa thông tin
            LapTheDG ltdg = new LapTheDG();
            ltdg.setMaDG(MaDG);
            ltdg.setHoTenDG(HoTen);
            ltdg.setMaLoai(MaLoai);
            ltdg.setNgaySinhDG(NgaySinh);
            ltdg.setSDTDG(SDT);
            ltdg.setNgayLapThe(NgayLapThe);
            ltdg.setUpdateMode(true); // Chế độ chỉnh sửa
            ltdg.setVisible(true);
            dispose();           
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần sửa.");
        }
    }//GEN-LAST:event_btnSuaDGActionPerformed

    private void btnXoaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDGActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDSDocGia.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần xóa.");
            return;
        }

        String MaDG = tableModel.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa độc giả này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "delete from DOCGIA where MaDG = ?";
            try (Connection con = MyConnection.getConnection();
                 PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, MaDG);
                int rowsAffected = ps.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa độc giả thành công.");
                    tableModel.removeRow(selectedRow);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa độc giả thất bại.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Xóa độc giả thất bại: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaDGActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnPrintCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCardActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDSDocGia.getSelectedRow();
        if (selectedRow != -1) {
            String MaDG = tblDSDocGia.getValueAt(selectedRow, 0).toString();
            String HoTen = tblDSDocGia.getValueAt(selectedRow, 1).toString();

            // Gọi phương thức để tạo PDF
            createPDF(MaDG, HoTen);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn độc giả cần in thẻ.");
        }
    }//GEN-LAST:event_btnPrintCardActionPerformed
    private void createPDF(String maDG, String hoTen) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn vị trí lưu file PDF");
        fileChooser.setSelectedFile(new File("Card_" + maDG + ".pdf"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try {
                Document document = new Document();
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
                document.open();

                // Thêm font hỗ trợ tiếng Việt
                BaseFont bf = BaseFont.createFont("c:/windows/fonts/times.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                Font titleFont = new Font(bf, 30, Font.BOLD);
                Font contentFont = new Font(bf, 12, Font.NORMAL);

                // Vẽ tiêu đề
                String title = "THÔNG TIN ĐỘC GIẢ";
                Paragraph titleParagraph = new Paragraph(title, titleFont);
                titleParagraph.setAlignment(Element.ALIGN_CENTER);
                document.add(titleParagraph);
                document.add(new Paragraph("\n")); // Dòng trống

                // Thêm thông tin độc giả
                document.add(new Paragraph("Mã độc giả: " + maDG, contentFont));
                document.add(new Paragraph("Họ tên: " + hoTen, contentFont));

                // Lấy thông tin từ cơ sở dữ liệu
                String query = "SELECT * FROM DOCGIA WHERE MaDG = ?";
                try (Connection conn = MyConnection.getConnection(); 
                     PreparedStatement pstmt = conn.prepareStatement(query)) {
                    pstmt.setString(1, maDG);
                    ResultSet rs = pstmt.executeQuery();

                    if (rs.next()) {
                        String maLoai = rs.getString("MaLoai");
                        String ngaySinh = rs.getString("NgaySinh");
                        String sdt = rs.getString("SDT");
                        String ngayLapThe = rs.getString("NgayLapThe");
                        String ngayHetHan = rs.getString("NgayHetHan");

                        // Thêm các thông tin vào PDF
                        document.add(new Paragraph("Loại độc giả: " + maLoai, contentFont));
                        document.add(new Paragraph("Ngày sinh: " + ngaySinh, contentFont));
                        document.add(new Paragraph("Số điện thoại: " + sdt, contentFont));
                        document.add(new Paragraph("Ngày lập thẻ: " + ngayLapThe, contentFont));
                        document.add(new Paragraph("Ngày hết hạn: " + ngayHetHan, contentFont));
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }

                // Tạo mã QR
                QRCodeWriter qrCodeWriter = new QRCodeWriter();
                BitMatrix qrBitMatrix = qrCodeWriter.encode(maDG, BarcodeFormat.QR_CODE, 100, 100);
                BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(qrBitMatrix);
                ByteArrayOutputStream qrBaos = new ByteArrayOutputStream();
                ImageIO.write(qrImage, "png", qrBaos);
                com.itextpdf.text.Image qrPdfImage = com.itextpdf.text.Image.getInstance(qrBaos.toByteArray());

                // Tạo mã vạch
                Barcode128 barcode128 = new Barcode128();
                barcode128.setCode(maDG);
                com.itextpdf.text.Image barcodeImage = barcode128.createImageWithBarcode(writer.getDirectContent(), null, null);

                // Thêm mã QR và mã vạch vào PDF
                // Tạo bảng và thiết lập thuộc tính
                PdfPTable table = new PdfPTable(2);
                table.setWidthPercentage(100);
                // Tạo mã QR
                PdfPCell qrCell = new PdfPCell(qrPdfImage);
                qrCell.setHorizontalAlignment(Element.ALIGN_CENTER); // Căn giữa
                qrCell.setVerticalAlignment(Element.ALIGN_MIDDLE); // Căn giữa theo chiều dọc
                qrCell.setBorder(PdfPCell.NO_BORDER); // Loại bỏ viền cho mã QR
                // Thêm mã QR vào bảng
                table.addCell(qrCell);

                // Tạo ô cho mã vạch
                PdfPCell barcodeCell = new PdfPCell(barcodeImage);
                barcodeCell.setHorizontalAlignment(Element.ALIGN_CENTER); // Căn giữa
                barcodeCell.setVerticalAlignment(Element.ALIGN_MIDDLE); // Căn giữa theo chiều dọc
                barcodeCell.setBorder(PdfPCell.NO_BORDER); // Loại bỏ viền
                // Thêm ô mã vạch vào bảng
                table.addCell(barcodeCell);
                // Thêm một dòng trống trước khi thêm bảng
                document.add(new Paragraph("\n"));
                document.add(table);

                document.close();
                JOptionPane.showMessageDialog(this, "Đã tạo PDF: " + fileToSave.getAbsolutePath());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi tạo PDF: " + e.getMessage());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapTheDG;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnPrintCard;
    private javax.swing.JButton btnSuaDG;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThuTienPhat;
    private javax.swing.JButton btnXoaDG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDSDocGia;
    // End of variables declaration//GEN-END:variables
}
