/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;
/**
 *
 * @author ADMIN
 */
public class QLKiemKe extends javax.swing.JFrame {

    /**
     * Creates new form QLKiemKe
     */
    public QLKiemKe() {
        initComponents();
        loadData();
    }
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblKiemKe.getModel();
        model.setRowCount(0); // Xóa dữ liệu hiện có

        try {
            // Thiết lập kết nối
            Connection conn = MyConnection.getConnection();
            Statement stmt = conn.createStatement();
            String sql = "SELECT p.MaPhieuKK, p.NgayLap, n.HoTen " +
                         "FROM PHIEUKIEMKE p " +
                         "JOIN NhanVien n ON p.MaNV = n.MaNV"; // Cập nhật tên bảng và trường theo nhu cầu
            
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String maPhieuKK = rs.getString("MaPhieuKK");
                String ngayLap = rs.getString("NgayLap");
                String tenNV = rs.getString("HoTen");

                model.addRow(new Object[]{maPhieuKK, ngayLap, tenNV});
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKiemKe = new javax.swing.JTable();
        btnLapPhieuKiemKe = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnChinhSua = new javax.swing.JButton();
        btnQLSach = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 16, 156));
        jLabel2.setText("Kiểm kê");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 15, -1, -1));

        tblKiemKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phiếu kiểm kê", "Ngày lập", "Người lập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKiemKe);
        if (tblKiemKe.getColumnModel().getColumnCount() > 0) {
            tblKiemKe.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 1160, 510));

        btnLapPhieuKiemKe.setBackground(new java.awt.Color(51, 153, 0));
        btnLapPhieuKiemKe.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnLapPhieuKiemKe.setForeground(new java.awt.Color(255, 255, 255));
        btnLapPhieuKiemKe.setText("Lập phiếu kiểm kê");
        btnLapPhieuKiemKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieuKiemKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapPhieuKiemKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 50));

        btnXoa.setBackground(new java.awt.Color(51, 153, 0));
        btnXoa.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 700, -1, 30));

        btnChinhSua.setBackground(new java.awt.Color(51, 153, 0));
        btnChinhSua.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnChinhSua.setForeground(new java.awt.Color(255, 255, 255));
        btnChinhSua.setText("Chỉnh sửa");
        btnChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 700, -1, 30));

        btnQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnQLSach.png"))); // NOI18N
        btnQLSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnKiemKe.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLKiemKe.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblKiemKe.getSelectedRow(); // Lấy dòng được chọn
        if (selectedRow != -1) { // Kiểm tra xem có dòng nào được chọn không
            String maPhieuKK = tblKiemKe.getValueAt(selectedRow, 0).toString(); // Lấy mã phiếu kiểm kê

            // Hiển thị hộp thoại xác nhận
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Xác nhận xóa", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    // Kết nối cơ sở dữ liệu
                    Connection conn = MyConnection.getConnection();

                    // Xóa dữ liệu trong CTPhieuKK
                    String sqlCT = "DELETE FROM CTPhieuKK WHERE MaPhieuKK = ?";
                    PreparedStatement pstmtCT = conn.prepareStatement(sqlCT);
                    pstmtCT.setString(1, maPhieuKK);
                    pstmtCT.executeUpdate();

                    // Xóa dữ liệu trong PhieuKiemKe
                    String sqlPhieu = "DELETE FROM PhieuKiemKe WHERE MaPhieuKK = ?";
                    PreparedStatement pstmtPhieu = conn.prepareStatement(sqlPhieu);
                    pstmtPhieu.setString(1, maPhieuKK);
                    pstmtPhieu.executeUpdate();

                    // Đóng kết nối
                    pstmtCT.close();
                    pstmtPhieu.close();
                    conn.close();

                    // Cập nhật lại bảng
                    loadData(); // Gọi lại phương thức loadData để cập nhật bảng
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
                } catch (Exception e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa không thành công: " + e.getMessage());
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblKiemKe.getSelectedRow(); // Lấy dòng được chọn
        if (selectedRow != -1) {
            String maPhieuKK = tblKiemKe.getValueAt(selectedRow, 0).toString(); // Lấy Mã Phiếu Kiểm Kê
            String ngayLap = tblKiemKe.getValueAt(selectedRow, 1).toString(); // Lấy Ngày Lập

            // Mở form LapPhieuKiemKe và thiết lập giá trị
            LapPhieuKiemKe lapPhieuKiemKe = new LapPhieuKiemKe();
            lapPhieuKiemKe.setTxtMaKK(maPhieuKK);
            lapPhieuKiemKe.setTxtNgayLap(ngayLap);

            // Tải chi tiết từ CTPHIEUKK vào bảng
            DefaultTableModel model = new DefaultTableModel(new Object[]{"Mã sách", "Tên sách", "Số lượng", "Tình trạng"}, 0);
            String detailQuery = "SELECT MaSach, SoLuongKK, TinhTrang FROM CTPHIEUKK WHERE MaPhieuKK = ?";

            try (Connection connection = MyConnection.getConnection();
                 PreparedStatement psDetail = connection.prepareStatement(detailQuery)) {
                psDetail.setString(1, maPhieuKK);
                ResultSet rsDetail = psDetail.executeQuery();

                while (rsDetail.next()) {
                    String maSach = rsDetail.getString("MaSach");
                    int soLuong = rsDetail.getInt("SoLuongKK");
                    String tinhTrang = rsDetail.getString("TinhTrang");

                    // Truy vấn để lấy tên sách từ bảng SACH
                    String tenSach = "";
                    String bookQuery = "SELECT TenSach FROM SACH WHERE MaSach = ?";
                    try (PreparedStatement psBook = connection.prepareStatement(bookQuery)) {
                        psBook.setString(1, maSach);
                        ResultSet rsBook = psBook.executeQuery();
                        if (rsBook.next()) {
                            tenSach = rsBook.getString("TenSach");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Lỗi khi lấy tên sách: " + e.getMessage());
                    }

                    model.addRow(new Object[]{maSach, tenSach, soLuong, tinhTrang}); // Thêm tên sách vào mô hình
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi lấy chi tiết phiếu kiểm kê: " + e.getMessage());
            }

            lapPhieuKiemKe.setTblCTKK(model); // Gọi phương thức để thiết lập bảng
            lapPhieuKiemKe.setVisible(true); // Hiển thị form
            // Đóng trang hiện tại
            this.dispose(); // Đóng form QLKiemKe
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa.");
        }
    }//GEN-LAST:event_btnChinhSuaActionPerformed

    private void btnLapPhieuKiemKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieuKiemKeActionPerformed
        // TODO add your handling code here:
        LapPhieuKiemKe lpkk = new LapPhieuKiemKe();
        lpkk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLapPhieuKiemKeActionPerformed

    private void btnQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSachActionPerformed
        // TODO add your handling code here:
        QuanLySach newPage = new QuanLySach();
        newPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKiemKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChinhSua;
    private javax.swing.JButton btnLapPhieuKiemKe;
    private javax.swing.JButton btnQLSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKiemKe;
    // End of variables declaration//GEN-END:variables
}
