/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;
/**
 *
 * @author ADMIN
 */
public class QLMuonTra extends javax.swing.JFrame {

    /**
     * Creates new form QLMuonTra
     */
    public QLMuonTra() {
        initComponents();
         loadData();
    }
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblMuonTra.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        String query = "SELECT p.MaPhieu, p.TinhTrang, p.NgayMuon, p.NgayTra, p.HanTra, "
                     + "d.HoTen AS HoTenDocGia, n.HoTen AS HoTenNhanVien "
                     + "FROM PHIEUMUONTRA p "
                     + "JOIN DocGia d ON p.MaDG = d.MaDG "
                     + "JOIN NHANVIEN n ON p.MaNV = n.MaNV";

        try (Connection connection = MyConnection.getConnection();
             PreparedStatement ps = connection.prepareStatement(query);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                String maPhieu = rs.getString("MaPhieu");
                String hoTenDocGia = rs.getString("HoTenDocGia");
                String tinhTrang = rs.getString("TinhTrang");
                String ngayMuon = rs.getString("NgayMuon");
                String ngayTra = rs.getString("NgayTra");
                String hanTra = rs.getString("HanTra");
                String hoTenNhanVien = rs.getString("HoTenNhanVien");

                model.addRow(new Object[]{maPhieu, hoTenDocGia, tinhTrang, ngayMuon, hanTra, ngayTra, hoTenNhanVien});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMuonTra = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        btnThuTienPhat = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnPhieuMuon = new javax.swing.JButton();
        btnPhieuTra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 16, 156));
        jLabel2.setText("Quản lí mượn trả");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        tblMuonTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Họ tên độc giả", "Tình trạng", "Ngày mượn", "Hạn trả", "Ngày trả", "Người lập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMuonTra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 1170, 400));

        btnXoa.setBackground(new java.awt.Color(51, 153, 0));
        btnXoa.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 600, -1, -1));

        btnDocGia.setBackground(new java.awt.Color(255, 255, 255));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(null);
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        btnMuonTra.setBackground(new java.awt.Color(255, 255, 255));
        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnMuonTra(1).png"))); // NOI18N
        btnMuonTra.setBorder(null);
        getContentPane().add(btnMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThuTienPhat.png"))); // NOI18N
        btnThuTienPhat.setBorder(null);
        btnThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btnPhieuMuon.setBackground(new java.awt.Color(255, 255, 255));
        btnPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnPhieuMuon_noclick.png"))); // NOI18N
        btnPhieuMuon.setBorder(null);
        btnPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuMuonActionPerformed(evt);
            }
        });
        getContentPane().add(btnPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btnPhieuTra.setBackground(new java.awt.Color(255, 255, 255));
        btnPhieuTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnPhieuTra_noclick.png"))); // NOI18N
        btnPhieuTra.setBorder(null);
        btnPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnPhieuTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLKiemKe.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMuonTra.getSelectedRow(); // Lấy dòng được chọn
            if (selectedRow != -1) {
                String maPhieu = tblMuonTra.getValueAt(selectedRow, 0).toString(); // Lấy Mã Phiếu
                String tinhTrang = tblMuonTra.getValueAt(selectedRow, 2).toString(); // Lấy Tình Trạng

                // Kiểm tra tình trạng phiếu
                if ("Đang mượn".equalsIgnoreCase(tinhTrang)) {
                    JOptionPane.showMessageDialog(this, "Không thể xóa phiếu khi tình trạng đang mượn.");
                    return;
                }

                // Xác nhận xóa
                int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // Nếu người dùng chọn không, thoát khỏi phương thức
                }

                // Bắt đầu xóa từ CTPHIEUMUONTRA
                String deleteCTQuery = "DELETE FROM CTPHIEUMUONTRA WHERE MaPhieu = ?";
                try (Connection connection = MyConnection.getConnection();
                     PreparedStatement psCT = connection.prepareStatement(deleteCTQuery)) {
                    psCT.setString(1, maPhieu);
                    psCT.executeUpdate();
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Lỗi khi xóa chi tiết phiếu: " + e.getMessage());
                    return;
                }

                // Xóa phiếu khỏi PHIEUMUONTRA
                String deletePhieuQuery = "DELETE FROM PHIEUMUONTRA WHERE MaPhieu = ?";
                try (Connection connection = MyConnection.getConnection();
                     PreparedStatement psPhieu = connection.prepareStatement(deletePhieuQuery)) {
                    psPhieu.setString(1, maPhieu);
                    psPhieu.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Xóa phiếu thành công!");
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Lỗi khi xóa phiếu: " + e.getMessage());
                }

                // Tải lại dữ liệu vào bảng
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.");
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuMuonActionPerformed
        // TODO add your handling code here:
        QLMuon qLMuon = new QLMuon();
        qLMuon.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPhieuMuonActionPerformed

    private void btnPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuTraActionPerformed
        // TODO add your handling code here:
        QLTra qLTra = new QLTra();
        qLTra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPhieuTraActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienPhatActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttp = new ThuTienPhat();
        ttp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThuTienPhatActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMuonTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnPhieuMuon;
    private javax.swing.JButton btnPhieuTra;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThuTienPhat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMuonTra;
    // End of variables declaration//GEN-END:variables
}
