/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.Barcode128;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import com.itextpdf.text.BaseColor; // Để sử dụng BaseColor
import com.itextpdf.text.Font; // Để sử dụng Font
import com.itextpdf.text.pdf.PdfPTable; // Để tạo bảng trong PDF
import javax.swing.JFileChooser; // Để sử dụng JFileChooser
import java.awt.print.PrinterException; // Để xử lý in ấn
import java.awt.print.PrinterJob; // Để sử dụng PrinterJob
import java.awt.print.Printable; // Để thực hiện in
import java.awt.Graphics; // Để vẽ đồ họa
import java.awt.print.PageFormat; // Để định dạng trang in
import java.awt.image.BufferedImage; // Để xử lý ảnh
import javax.imageio.ImageIO; // Để ghi ảnh
import com.google.zxing.BarcodeFormat; // Để định dạng mã vạch
import com.google.zxing.WriterException; // Để xử lý lỗi viết mã vạch
import com.google.zxing.common.BitMatrix; // Để sử dụng ma trận
import com.google.zxing.qrcode.QRCodeWriter; // Để tạo mã QR
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import java.io.File;
/**
 *
 * @author Ngoc Han
 */
public class QLMuon extends javax.swing.JFrame {

    /**
     * Creates new form QLMuon
     */
    public QLMuon() {
        initComponents();
        setCurrentDate();
    }
    private void setCurrentDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date currentDate = new Date();
        txtNgayMuon.setText(sdf.format(currentDate));

        // Tính ngày hạn trả (ngày mượn + 7 ngày)
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        calendar.add(Calendar.DAY_OF_MONTH, 7); // Cộng thêm 7 ngày
        txtHanTra.setText(sdf.format(calendar.getTime())); // Đặt hạn trả
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTra = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTPhieuMuon = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        txtMaPhieu = new javax.swing.JTextField();
        txtHoTenDG = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        txtHanTra = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        btnThuTienPhat = new javax.swing.JButton();
        btnThongKe1 = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        txtSoLuongHienCo = new javax.swing.JTextField();
        txtSoLuongMuon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnPhieuTra_noclick.png"))); // NOI18N
        btnTra.setBorder(null);
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 98, 138, 44));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnTimKiem.png"))); // NOI18N
        btnTimKiem.setBorder(null);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 210, 50));

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnLuu.png"))); // NOI18N
        btnLuu.setBorder(null);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 670, -1, -1));

        tblCTPhieuMuon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCTPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCTPhieuMuon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 620, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThem.png"))); // NOI18N
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 590, -1, 50));

        txtMaPhieu.setBorder(null);
        getContentPane().add(txtMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 270, 30));

        txtHoTenDG.setBorder(null);
        getContentPane().add(txtHoTenDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 253, 270, 30));

        txtNgayMuon.setBorder(null);
        getContentPane().add(txtNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, 270, 30));

        txtHanTra.setBorder(null);
        getContentPane().add(txtHanTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 258, 270, 30));

        txtMaSach.setBorder(null);
        getContentPane().add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 328, 270, 30));

        txtTenSach.setBorder(null);
        getContentPane().add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 395, 270, 30));

        btnThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThuTienPhat.png"))); // NOI18N
        btnThuTienPhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 65));

        btnThongKe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe1.setBorder(null);
        btnThongKe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKe1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        btnDocGia.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnDocGia.setForeground(new java.awt.Color(1, 16, 156));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 70));

        txtSoLuongHienCo.setBorder(null);
        getContentPane().add(txtSoLuongHienCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 460, 270, 30));

        txtSoLuongMuon.setBorder(null);
        getContentPane().add(txtSoLuongMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 525, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLMuon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();

        // Kiểm tra tính hợp lệ của dữ liệu.
        if (maSach.isEmpty() && tenSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách hoặc tên sách để tìm.");
            return;
        }
        String query = "";
        if (!maSach.isEmpty()) {
            // Tìm kiếm theo mã sách.
            query = "SELECT TenSach, SoLuongHienCo FROM SACH WHERE MaSach = ?";
        } else if (!tenSach.isEmpty()) {
            // Tìm kiếm theo tên sách.
            query = "SELECT MaSach, SoLuongHienCo FROM SACH WHERE TenSach = ?";
        }

        try (Connection connection = MyConnection.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(query)) {

            if (!maSach.isEmpty()) {
                preparedStatement.setString(1, maSach);
            } else if (!tenSach.isEmpty()) {
                preparedStatement.setString(1, tenSach);
            }

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                if (!maSach.isEmpty()) {
                    // Hiển thị tên sách và số lượng hiện có.
                    txtTenSach.setText(resultSet.getString("TenSach"));
                    txtSoLuongHienCo.setText(String.valueOf(resultSet.getInt("SoLuongHienCo")));
                } else if (!tenSach.isEmpty()) {
                    // Hiển thị mã sách và số lượng hiện có.
                    txtMaSach.setText(resultSet.getString("MaSach"));
                    txtSoLuongHienCo.setText(String.valueOf(resultSet.getInt("SoLuongHienCo")));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách.");
            }
        } catch (SQLException e) {
            // Nếu có lỗi xảy ra trong quá trình kết nối hoặc truy vấn cơ sở dữ liệu.
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ các ô nhập liệu
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String soLuongMuon = txtSoLuongMuon.getText();

        // Kiểm tra tính hợp lệ của dữ liệu
        if (maSach.isEmpty() || tenSach.isEmpty() || soLuongMuon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
            return;
        }

        // Thêm hàng vào bảng
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCTPhieuMuon.getModel();
        model.addRow(new Object[]{maSach, tenSach, soLuongMuon});

        // Xóa dữ liệu trong các ô nhập liệu để chuẩn bị cho lần nhập tiếp theo
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtSoLuongHienCo.setText("");
        txtSoLuongMuon.setText("");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String maPhieu = txtMaPhieu.getText();
        String hoTenDocGia = txtHoTenDG.getText();
        String maDocGia = null;

        // Bước 1: Lấy ID độc giả
        String queryDocGia = "SELECT MaDG FROM DocGia WHERE HoTen = ?";
        try (Connection connection = MyConnection.getConnection();
             PreparedStatement ps = connection.prepareStatement(queryDocGia)) {
            ps.setString(1, hoTenDocGia);
            ResultSet resultSet = ps.executeQuery();

            if (resultSet.next()) {
                maDocGia = resultSet.getString("MaDG");
            } else {
                JOptionPane.showMessageDialog(this, "Độc giả chưa lập thẻ.");
                return;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
            return;
        }
        // Kiểm tra phiếu mượn quá hạn
        String overdueQuery = "SELECT COUNT(*) AS OverdueBooks FROM PHIEUMUONTRA WHERE MaDG = ? AND TinhTrang = 'đang mượn' AND HanTra < GETDATE()";
        try (Connection connection = MyConnection.getConnection();
             PreparedStatement ps = connection.prepareStatement(overdueQuery)) {
            ps.setString(1, maDocGia);
            ResultSet resultSet = ps.executeQuery();

            if (resultSet.next()) {
                int overdueBooks = resultSet.getInt("OverdueBooks");
                if (overdueBooks > 0) {
                    JOptionPane.showMessageDialog(this, "Độc giả có sách mượn quá hạn. Vui lòng trả sách trước khi mượn mới.");
                    return;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
            return;
        }
        // Bước 3: Chèn phiếu mượn
        String insertPhieuMuon = "INSERT INTO PHIEUMUONTRA VALUES (?, null, null, null, null, ?, 'NVTT004')";
        try (Connection connection = MyConnection.getConnection();
             PreparedStatement ps2 = connection.prepareStatement(insertPhieuMuon)) {
            ps2.setString(1, maPhieu);
            ps2.setString(2, maDocGia);
            ps2.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu phiếu mượn: " + e.getMessage());
            return;
        }
        // Bước 4: Chèn chi tiết phiếu mượn
        String insertCTPhieuMuon = "INSERT INTO CTPHIEUMUONTRA VALUES (?, ?, ?)";
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCTPhieuMuon.getModel();
        boolean hasError = false; // Biến kiểm tra lỗi
        for (int i = 0; i < model.getRowCount(); i++) {
            String maSach = (String) model.getValueAt(i, 0);
            String soLuong = model.getValueAt(i, 2).toString();

            try (Connection connection = MyConnection.getConnection();
                 PreparedStatement ps3 = connection.prepareStatement(insertCTPhieuMuon)) {
                ps3.setString(1, soLuong);
                ps3.setString(2, maSach);
                ps3.setString(3, maPhieu);
                ps3.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu chi tiết phiếu mượn: " + e.getMessage());
                break;
            }
        }
        if (!hasError) {
            // Sau khi lưu thành công, hỏi người dùng có muốn in không
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn in phiếu mượn không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    // Gọi phương thức in
                    printReceipt(maPhieu, hoTenDocGia);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi khi in phiếu: " + e.getMessage());
                }
            }
            // Gọi hàm xóa dữ liệu
            clearTextFields();
            JOptionPane.showMessageDialog(this, "Lưu phiếu mượn thành công!");
        }
    }//GEN-LAST:event_btnLuuActionPerformed
    private void printReceipt(String maPhieu, String hoTenDocGia) throws Exception {
        // Khởi tạo tài liệu PDF
        Document document = new Document();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn vị trí lưu file PDF");
        fileChooser.setSelectedFile(new File("PhieuMuon_" + maPhieu + ".pdf"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
            document.open();

            // Thêm font hỗ trợ tiếng Việt
            BaseFont bf = BaseFont.createFont("c:/windows/fonts/times.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font titleFont = new Font(bf, 30, Font.BOLD);
            Font contentFont = new Font(bf, 12, Font.NORMAL);

            // Vẽ tiêu đề
            Paragraph titleParagraph = new Paragraph("PHIẾU MƯỢN SÁCH", titleFont);
            titleParagraph.setAlignment(Element.ALIGN_CENTER);
            document.add(titleParagraph);

            document.add(new Paragraph("Mã phiếu: " + maPhieu, contentFont));
            document.add(new Paragraph("Họ tên độc giả: " + hoTenDocGia, contentFont));
            document.add(new Paragraph("Ngày mượn: " + txtNgayMuon.getText(), contentFont));
            document.add(new Paragraph("Hạn trả: " + txtHanTra.getText(), contentFont));
            document.add(new Paragraph("\n")); // Dòng trống

            // Thêm bảng chi tiết
            PdfPTable table = new PdfPTable(3);
            table.addCell(new Phrase("Mã sách", contentFont));
            table.addCell(new Phrase("Tên sách", contentFont));
            table.addCell(new Phrase("Số lượng", contentFont));

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCTPhieuMuon.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String maSach = (String) model.getValueAt(i, 0);
                String tenSach = (String) model.getValueAt(i, 1);
                String soLuong = model.getValueAt(i, 2).toString();
                table.addCell(new Phrase(maSach, contentFont));
                table.addCell(new Phrase(tenSach, contentFont));
                table.addCell(new Phrase(soLuong, contentFont));
            }
            document.add(table);

            // Thêm mã vạch
            Barcode128 barcode128 = new Barcode128();
            barcode128.setCode(maPhieu);
            com.itextpdf.text.Image barcodeImage = barcode128.createImageWithBarcode(writer.getDirectContent(), null, null);
            document.add(barcodeImage);

            document.close();
            JOptionPane.showMessageDialog(this, "Đã tạo PDF: " + fileToSave.getAbsolutePath());
        }
    }
    private void clearTextFields() {
        txtMaPhieu.setText("");
        txtHoTenDG.setText("");
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtSoLuongHienCo.setText("");
        txtSoLuongMuon.setText("");
        txtNgayMuon.setText("");
        txtHanTra.setText("");

        // Xóa bảng chi tiết
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCTPhieuMuon.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng
    }
    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
        QLTra qLTra = new QLTra();
        qLTra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTraActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);

        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienPhatActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttp = new ThuTienPhat();
        ttp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThuTienPhatActionPerformed

    private void btnThongKe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKe1ActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKe1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongKe1;
    private javax.swing.JButton btnThuTienPhat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCTPhieuMuon;
    private javax.swing.JTextField txtHanTra;
    private javax.swing.JTextField txtHoTenDG;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtSoLuongHienCo;
    private javax.swing.JTextField txtSoLuongMuon;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
