/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;

/**
 *
 * @author dangt
 */
public class QLNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QLNhanVien
     */
    private DefaultTableModel tableModel;
    
    public QLNhanVien() {
        initComponents();
        loadDataToTable();
    }
    private void loadDataToTable() {
        String query = "select * from NHANVIEN";
        ResultSet rs = MyConnection.executeQuery(query);

        if (rs == null) {
            // Xử lý khi không lấy được dữ liệu
            return;
        }

        try {
            tableModel = (DefaultTableModel) tblDSNhanVien.getModel();
            tableModel.setRowCount(0); // Xóa các hàng cũ

            while (rs.next()) {
                String MaNV = rs.getString("MaNV");
                String HoTen = rs.getString("HoTen");
                String NgaySinh = rs.getString("NgaySinh");
                String DiaChi = rs.getString("DiaChi");
                String SDT = rs.getString("SDT");
                String Email = rs.getString("Email");
                String NgayVaoLam = rs.getString("NgayVaoLam");
                String MaBP = rs.getString("MaBP");
                String MatKhau = rs.getString("MatKhau");

                // Thêm dòng mới vào JTable
                tableModel.addRow(new Object[]{MaNV, HoTen, NgaySinh, DiaChi, SDT, Email, NgayVaoLam, MaBP, MatKhau});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemNhanVien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSNhanVien = new javax.swing.JTable();
        btnSuaNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThemNhanVien.setBackground(new java.awt.Color(15, 166, 85));
        btnThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThemNhanVien.png"))); // NOI18N
        btnThemNhanVien.setToolTipText("");
        btnThemNhanVien.setBorder(null);
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 170, 30));

        tblDSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Ngày sinh", "Địa chỉ", "SDT", "Email", "Ngày vào làm", "Bộ phận", "Mật khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDSNhanVien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 1180, 460));

        btnSuaNV.setBackground(new java.awt.Color(15, 166, 85));
        btnSuaNV.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnSuaNV.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaNV.setText("Chỉnh sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 700, 120, 40));

        btnXoaNV.setBackground(new java.awt.Color(255, 0, 0));
        btnXoaNV.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnXoaNV.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaNV.setText("Xoá");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 700, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/QuanLyNhanVien.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        // TODO add your handling code here:
        ThemNV themnv = new ThemNV();
        themnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDSNhanVien.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa.");
            return;
        }

        String MaNV = tableModel.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhân viên này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "delete from NHANVIEN where MaNV = ?";
            try (Connection con = MyConnection.getConnection();
                 PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, MaNV);
                int rowsAffected = ps.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công.");
                    tableModel.removeRow(selectedRow);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDSNhanVien.getSelectedRow();
        if (selectedRow != -1) { 
            // Lấy thông tin từ bảng
            Object objMaNV = tblDSNhanVien.getValueAt(selectedRow, 0);
            Object objHoTen = tblDSNhanVien.getValueAt(selectedRow, 1);
            Object objNgaySinh = tblDSNhanVien.getValueAt(selectedRow, 2);
            Object objDiaChi = tblDSNhanVien.getValueAt(selectedRow, 3);
            Object objSDT = tblDSNhanVien.getValueAt(selectedRow, 4);
            Object objEmail = tblDSNhanVien.getValueAt(selectedRow, 5);
            Object objNgayVaoLam = tblDSNhanVien.getValueAt(selectedRow, 6);
            Object objMaBP = tblDSNhanVien.getValueAt(selectedRow, 7);
            Object objMatKhau = tblDSNhanVien.getValueAt(selectedRow, 8);
            //kiem tra xem du lieu co null hay khong
            String MaNV = objMaNV != null ? objMaNV.toString() : "";
            String HoTen = objHoTen != null ? objHoTen.toString() : "";
            String NgaySinh = objNgaySinh != null ? objNgaySinh.toString() : "";
            String DiaChi = objDiaChi != null ? objDiaChi.toString() : "";
            String SDT = objSDT != null ? objSDT.toString() : "";
            String Email = objEmail != null ? objEmail.toString() : "";
            String NgayVaoLam = objNgayVaoLam != null ? objNgayVaoLam.toString() : "";
            String MaBP = objMaBP != null ? objMaBP.toString() : "";
            String MatKhau = objMatKhau != null ? objMatKhau.toString() : "";            
            
            ThemNV themnv = new ThemNV();
            themnv.setMaNV(MaNV);
            themnv.setHoTen(HoTen);
            themnv.setNgaySinh(NgaySinh);
            themnv.setDiaChi(DiaChi);
            themnv.setSDT(SDT);
            themnv.setEmail(Email);
            themnv.setNgayVaoLam(NgayVaoLam);
            themnv.setMaBP(MaBP);
            themnv.setMatKhau(MatKhau);
            themnv.setUpdateMode(true); 
            themnv.setVisible(true);
            dispose();               
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa thông tin.");
        }
    }//GEN-LAST:event_btnSuaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSNhanVien;
    // End of variables declaration//GEN-END:variables
}
