/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.Connection; 
import smartlibrarydb.MyConnection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ngoc Han
 */
public class QLTra extends javax.swing.JFrame {

    /**
     * Creates new form QLTra
     */
    public QLTra() {
        initComponents();
        setCurrentDate();
    }
    private void setCurrentDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date currentDate = new java.util.Date();
        txtNgayTra.setText(sdf.format(currentDate));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMuon = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTPhieuMuon = new javax.swing.JTable();
        txtMaPhieu = new javax.swing.JTextField();
        txtHoTenDocGia = new javax.swing.JTextField();
        btnDocGia = new javax.swing.JButton();
        txtNgayMuon = new javax.swing.JTextField();
        btnThuTienPhat = new javax.swing.JButton();
        txtHanTra = new javax.swing.JTextField();
        btnThongKe = new javax.swing.JButton();
        txtNgayTra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMuon.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnPhieuMuon_noclick.png"))); // NOI18N
        btnMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 100, 130, 42));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnTimKiem.png"))); // NOI18N
        btnTimKiem.setToolTipText("");
        btnTimKiem.setBorder(null);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, -1, -1));

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnLuu.png"))); // NOI18N
        btnLuu.setBorder(null);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 610, -1, -1));

        tblCTPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCTPhieuMuon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 670, 470));

        txtMaPhieu.setBorder(null);
        getContentPane().add(txtMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 215, 270, 30));

        txtHoTenDocGia.setBorder(null);
        getContentPane().add(txtHoTenDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 270, 30));

        btnDocGia.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnDocGia.setForeground(new java.awt.Color(1, 16, 156));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 70));

        txtNgayMuon.setBorder(null);
        getContentPane().add(txtNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 380, 270, 30));

        btnThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThuTienPhat.png"))); // NOI18N
        btnThuTienPhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 65));

        txtHanTra.setBorder(null);
        getContentPane().add(txtHanTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 460, 270, 30));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        txtNgayTra.setBorder(null);
        getContentPane().add(txtNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 545, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLTra.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maPhieu = txtMaPhieu.getText();
        try {
            // Thiết lập kết nối cơ sở dữ liệu (thay thế bằng thông tin của bạn)
            Connection conn = MyConnection.getConnection();

            // Truy vấn PHIEUMUONTRA
            String sql = "SELECT * FROM PHIEUMUONTRA WHERE MaPhieu = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, maPhieu);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Điền thông tin vào các trường
                txtNgayMuon.setText(rs.getString("NgayMuon"));
                txtHanTra.setText(rs.getString("HanTra"));
                String maDocGia = rs.getString("MaDG");

                // Truy vấn DocGia để lấy họ tên
                String sqlDocGia = "SELECT HoTen FROM DocGia WHERE MaDG = ?";
                PreparedStatement pstmtDocGia = conn.prepareStatement(sqlDocGia);
                pstmtDocGia.setString(1, maDocGia);
                ResultSet rsDocGia = pstmtDocGia.executeQuery();
                if (rsDocGia.next()) {
                    txtHoTenDocGia.setText(rsDocGia.getString("HoTen"));
                }

                // Truy vấn CTPHIEUMUONTRA để lấy thông tin sách
                String sqlCTPM = "SELECT * FROM CTPHIEUMUONTRA WHERE MaPhieu = ?";
                PreparedStatement pstmtCTPM = conn.prepareStatement(sqlCTPM);
                pstmtCTPM.setString(1, maPhieu);
                ResultSet rsCTPM = pstmtCTPM.executeQuery();

                DefaultTableModel model = (DefaultTableModel) tblCTPhieuMuon.getModel();
                model.setRowCount(0); // Xóa hàng hiện có

                while (rsCTPM.next()) {
                    String maSach = rsCTPM.getString("MaSach");
                    int soLuong = rsCTPM.getInt("SoLuongMuon");

                    // Truy vấn SACH để lấy tên sách
                    String sqlSach = "SELECT TenSach FROM SACH WHERE MaSach = ?";
                    PreparedStatement pstmtSach = conn.prepareStatement(sqlSach);
                    pstmtSach.setString(1, maSach);
                    ResultSet rsSach = pstmtSach.executeQuery();
                    String tenSach = "";
                    if (rsSach.next()) {
                        tenSach = rsSach.getString("TenSach");
                    }

                    // Thêm hàng vào bảng
                    model.addRow(new Object[]{maSach, tenSach, soLuong});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mã phiếu không tìm thấy.");
            }

            // Đóng kết nối
            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu.");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        // Lấy mã phiếu và ngày trả từ các trường văn bản
        String maPhieu = txtMaPhieu.getText();
        String ngayTra = txtNgayTra.getText();

        // Kết nối đến cơ sở dữ liệu
        try {
            Connection conn = MyConnection.getConnection();

            // Câu lệnh SQL để cập nhật trạng thái phiếu mượn
            String sql = "UPDATE PHIEUMUONTRA SET TinhTrang = N'Đã trả', NgayTra = ? WHERE MaPhieu = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, ngayTra);
            pstmt.setString(2, maPhieu);

            // Thực hiện cập nhật
            int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công.");
            } else {
                JOptionPane.showMessageDialog(this, "Mã phiếu không tồn tại.");
            }

            // Đóng kết nối
            pstmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cập nhật dữ liệu.");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonActionPerformed
        // TODO add your handling code here:
        QLMuon qLMuon = new QLMuon();
        qLMuon.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMuonActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienPhatActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttp = new ThuTienPhat();
        ttp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThuTienPhatActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMuon;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThuTienPhat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCTPhieuMuon;
    private javax.swing.JTextField txtHanTra;
    private javax.swing.JTextField txtHoTenDocGia;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    // End of variables declaration//GEN-END:variables
}
