/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;
/**
 *
 * @author ADMIN
 */
public class QuanLySach extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySach
     */
    public QuanLySach() {
        initComponents();
        loadDataToTable();
        addEventHandlers();
    }
    public void loadDataToTable() {
        Connection conn = MyConnection.getConnection();
        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0); // Clear the existing data

        String sql = "SELECT MaSach, TenSach, SoLuongHienCo, (SELECT TenTG FROM TACGIA WHERE TACGIA.MaTG = SACH.MaTG) AS TenTG FROM SACH";

        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String maSach = rs.getString("MaSach");
                String tenSach = rs.getString("TenSach");
                int soLuongHienCo = rs.getInt("SoLuongHienCo");
                String tenTG = rs.getString("TenTG");

                model.addRow(new Object[]{maSach, tenSach, tenTG, soLuongHienCo});
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void clearInputFields() {
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtTriGia.setText("");
        txtNXB.setText("");
        txtTongSL.setText("");
        txtSLHC.setText("");
        txtNhaXB.setText("");
        txtTacGia.setText("");
        txtLoaiSach.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        txtTenSach = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        txtTriGia = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        txtTongSL = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtSLHC = new javax.swing.JTextField();
        txtLoaiSach = new javax.swing.JTextField();
        txtNhaXB = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKiemKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Số lượng hiện có"
            }
        ));
        jScrollPane1.setViewportView(tblSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 670, -1));

        txtTenSach.setBorder(null);
        getContentPane().add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 270, 30));

        txtMaSach.setBorder(null);
        getContentPane().add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 270, 30));

        txtTriGia.setBorder(null);
        getContentPane().add(txtTriGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 270, 30));

        txtNXB.setBorder(null);
        getContentPane().add(txtNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 270, 30));

        txtTongSL.setBorder(null);
        getContentPane().add(txtTongSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 270, 30));

        txtTacGia.setBorder(null);
        getContentPane().add(txtTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 270, 30));

        txtSLHC.setBorder(null);
        getContentPane().add(txtSLHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 270, 30));

        txtLoaiSach.setBorder(null);
        getContentPane().add(txtLoaiSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 270, 30));

        txtNhaXB.setBorder(null);
        getContentPane().add(txtNhaXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 270, 30));

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnLuu.png"))); // NOI18N
        btnLuu.setBorder(null);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 550, -1, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnTimKiem.png"))); // NOI18N
        btnTim.setBorder(null);
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        getContentPane().add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, -1, 50));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnSua.png"))); // NOI18N
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 630, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnXoa.png"))); // NOI18N
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 630, -1, -1));

        btnKiemKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnKiemKe.png"))); // NOI18N
        btnKiemKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnKiemKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnKiemKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnQLSach.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 65));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLSach java.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String triGia = txtTriGia.getText();
        String namXB = txtNXB.getText();
        String tongSoLuong = txtTongSL.getText();
        String soLuongHienCo = txtSLHC.getText();
        String nhaXuatBan = txtNhaXB.getText();
        String tacGia = txtTacGia.getText();
        String loaiSach = txtLoaiSach.getText();

        // Kiểm tra tính hợp lệ của dữ liệu
        if (maSach.isEmpty() || tenSach.isEmpty() || triGia.isEmpty() || namXB.isEmpty() || tongSoLuong.isEmpty() || soLuongHienCo.isEmpty() || nhaXuatBan.isEmpty() || tacGia.isEmpty() || loaiSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
            return;
        }

        String query = "INSERT INTO SACH (MaSach, TenSach, TriGia, NamXB, TongSoLuong, SoLuongHienCo, MaNXB, MaTG, MaLoai) VALUES (?, ?, ?, ?, ?, ?, (SELECT MaNXB FROM NHAXB WHERE TenNXB = ?), (SELECT MaTG FROM TACGIA WHERE TenTG = ?), (SELECT MaLoai FROM LOAISACH WHERE TenLoai = ?))";

        try (Connection connection = MyConnection.getConnection();
            PreparedStatement preparedStatement = connection.prepareStatement(query)) {

            preparedStatement.setString(1, maSach);
            preparedStatement.setString(2, tenSach);
            preparedStatement.setDouble(3, Double.parseDouble(triGia));
            preparedStatement.setString(4, namXB);
            preparedStatement.setInt(5, Integer.parseInt(tongSoLuong));
            preparedStatement.setInt(6, Integer.parseInt(soLuongHienCo));
            preparedStatement.setString(7, nhaXuatBan);
            preparedStatement.setString(8, tacGia);
            preparedStatement.setString(9, loaiSach);

            int rowsInserted = preparedStatement.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Lưu sách thành công.");

                // Thêm dữ liệu vào bảng tblSach
                DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
                model.addRow(new Object[]{maSach, tenSach, tacGia, soLuongHienCo});
            }
        } catch (SQLException e) {
            // Nếu có lỗi xảy ra trong quá trình kết nối hoặc truy vấn cơ sở dữ liệu.
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();

        // Kiểm tra tính hợp lệ của dữ liệu.
        if (maSach.isEmpty() && tenSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách hoặc tên sách để tìm.");
            return;
        }

        String query = "SELECT SACH.MaSach, SACH.TenSach, SACH.TriGia, SACH.NamXB, SACH.TongSoLuong, SACH.SoLuongHienCo, NHAXB.TenNXB, TACGIA.TenTG, LOAISACH.TenLoai " +
        "FROM SACH " +
        "JOIN NHAXB ON SACH.MaNXB = NHAXB.MaNXB " +
        "JOIN TACGIA ON SACH.MaTG = TACGIA.MaTG " +
        "JOIN LOAISACH ON SACH.MaLoai = LOAISACH.MaLoai " +
        "WHERE SACH.MaSach = ? OR SACH.TenSach = ?";

        try (Connection connection = MyConnection.getConnection();
            PreparedStatement preparedStatement = connection.prepareStatement(query)) {

            if (!maSach.isEmpty()) {
                preparedStatement.setString(1, maSach);
                preparedStatement.setString(2, "");
            } else {
                preparedStatement.setString(1, "");
                preparedStatement.setString(2, tenSach);
            }

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                txtMaSach.setText(resultSet.getString("MaSach"));
                txtTenSach.setText(resultSet.getString("TenSach"));
                txtTriGia.setText(String.valueOf(resultSet.getDouble("TriGia")));
                txtNXB.setText(resultSet.getString("NamXB"));
                txtTongSL.setText(String.valueOf(resultSet.getInt("TongSoLuong")));
                txtSLHC.setText(String.valueOf(resultSet.getInt("SoLuongHienCo")));
                txtNhaXB.setText(resultSet.getString("TenNXB"));
                txtTacGia.setText(resultSet.getString("TenTG"));
                txtLoaiSach.setText(resultSet.getString("TenLoai"));
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách.");
            }
        } catch (SQLException e) {
            // Nếu có lỗi xảy ra trong quá trình kết nối hoặc truy vấn cơ sở dữ liệu.
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText().trim();
        if (maSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách để xóa.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sách này không?", "Xác Nhận Xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String deleteQuery = "DELETE FROM SACH WHERE MaSach = ?";

            try (Connection connection = MyConnection.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(deleteQuery)) {

                preparedStatement.setString(1, maSach);
                int affectedRows = preparedStatement.executeUpdate();

                if (affectedRows > 0) {
                    // Xóa khỏi JTable
                    DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
                    int rowCount = model.getRowCount();
                    for (int i = 0; i < rowCount; i++) {
                        if (model.getValueAt(i, 0).equals(maSach)) {
                            model.removeRow(i);
                            break;
                        }
                    }
                    // Xóa thành công
                    loadDataToTable();
                    JOptionPane.showMessageDialog(this, "Sách đã được xóa.");
                    clearInputFields(); // Xóa các trường nhập liệu
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy sách để xóa.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText().trim(); //bỏ khoảng trắng
        String tenSach = txtTenSach.getText().trim();
        String triGia = txtTriGia.getText().trim();
        String namXB = txtNXB.getText().trim();
        String tongSL = txtTongSL.getText().trim();
        String slHC = txtSLHC.getText().trim();
        String nhaXB = txtNhaXB.getText().trim();
        String tacGia = txtTacGia.getText().trim();
        String loaiSach = txtLoaiSach.getText().trim();

        if (maSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách để sửa.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa thông tin sách này không?", "Xác Nhận Sửa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String updateQuery = "UPDATE SACH SET TenSach = ?, TriGia = ?, NamXB = ?, TongSoLuong = ?, SoLuongHienCo = ?, " +
            "MaNXB = (SELECT MaNXB FROM NHAXB WHERE TenNXB = ?), MaTG = (SELECT MaTG FROM TACGIA WHERE TenTG = ?), " +
            "MaLoai = (SELECT MaLoai FROM LOAISACH WHERE TenLoai = ?) WHERE MaSach = ?";

            try (Connection connection = MyConnection.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(updateQuery)) {

                preparedStatement.setString(1, tenSach);
                preparedStatement.setDouble(2, Double.parseDouble(triGia));
                preparedStatement.setString(3, namXB);
                preparedStatement.setInt(4, Integer.parseInt(tongSL));
                preparedStatement.setInt(5, Integer.parseInt(slHC));
                preparedStatement.setString(6, nhaXB);
                preparedStatement.setString(7, tacGia);
                preparedStatement.setString(8, loaiSach);
                preparedStatement.setString(9, maSach);

                int affectedRows = preparedStatement.executeUpdate();

                if (affectedRows > 0) {
                    // Cập nhật JTable
                    /*
                    DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
                    int rowCount = model.getRowCount();
                    for (int i = 0; i < rowCount; i++) {
                        if (model.getValueAt(i, 0).equals(maSach)) {
                            model.setValueAt(tenSach, i, 1);
                            model.setValueAt(tacGia, i, 2); // Cập nhật tác giả ở cột tương ứng
                            model.setValueAt(slHC, i, 3);   // Cập nhật số lượng hiện có ở cột tương ứng
                            break;
                        }
                    }*/
                    loadDataToTable();
                    // Sửa thành công
                    JOptionPane.showMessageDialog(this, "Thông tin sách đã được sửa.");
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy sách để sửa.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnKiemKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemKeActionPerformed
        // TODO add your handling code here:
        QLKiemKe qLKiemKe = new QLKiemKe();
        qLKiemKe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKiemKeActionPerformed
    private void addEventHandlers() {
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Chỉ xử lý nhấp chuột đơn, bỏ qua nhấp chuột đôi
                if (evt.getClickCount() == 1) {
                    tblSachMouseClicked(evt);
                }
            }
        });
        btnXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        btnSua.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
    }

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {
        // Cập nhật các trường nhập liệu khi nhấp chuột đơn
        int selectedRow = tblSach.getSelectedRow();
        if (selectedRow >= 0) {
            String maSach = tblSach.getValueAt(selectedRow, 0).toString();
            
            String query = "SELECT MaSach, TenSach, TriGia, NamXB, TongSoLuong, SoLuongHienCo, " +
                           "(SELECT TenNXB FROM NHAXB WHERE MaNXB = SACH.MaNXB) AS NhaXB, " +
                           "(SELECT TenTG FROM TACGIA WHERE MaTG = SACH.MaTG) AS TacGia, " +
                           "(SELECT TenLoai FROM LOAISACH WHERE MaLoai = SACH.MaLoai) AS LoaiSach " +
                           "FROM SACH WHERE MaSach = ?";

            try (Connection connection = MyConnection.getConnection();
                 PreparedStatement preparedStatement = connection.prepareStatement(query)) {

                preparedStatement.setString(1, maSach);

                ResultSet resultSet = preparedStatement.executeQuery();

                if (resultSet.next()) {
                    txtMaSach.setText(resultSet.getString("MaSach"));
                    txtTenSach.setText(resultSet.getString("TenSach"));
                    txtTriGia.setText(String.valueOf(resultSet.getDouble("TriGia")));
                    txtNXB.setText(resultSet.getString("NamXB"));
                    txtTongSL.setText(String.valueOf(resultSet.getInt("TongSoLuong")));
                    txtSLHC.setText(String.valueOf(resultSet.getInt("SoLuongHienCo")));
                    txtNhaXB.setText(resultSet.getString("NhaXB"));
                    txtTacGia.setText(resultSet.getString("TacGia"));
                    txtLoaiSach.setText(resultSet.getString("LoaiSach"));
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin sách.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiemKe;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtLoaiSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtNhaXB;
    private javax.swing.JTextField txtSLHC;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTongSL;
    private javax.swing.JTextField txtTriGia;
    // End of variables declaration//GEN-END:variables

}
