/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import smartlibrarydb.MyConnection;
//
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.print.Printable;
import java.awt.print.PageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author ADMIN
 */
public class SachDuocMuon extends javax.swing.JFrame {

    /**
     * Creates new form SachDuocMuon
     */
    public SachDuocMuon() {
        initComponents();
        loadData();
    }
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblThongKeSachDuocMuon.getModel();
        model.setRowCount(0);  // Xóa dữ liệu cũ

        try (Connection conn = MyConnection.getConnection();
             CallableStatement stmt = conn.prepareCall("{call sp_ThongKeSachDuocMuon}")) {
             
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String maSach = rs.getString("MaSach");
                String tenSach = rs.getString("TenSach");
                int soLuongMuon = rs.getInt("SoLuongMuon");
                model.addRow(new Object[]{maSach, tenSach, soLuongMuon});
            }
            // Vẽ biểu đồ sau khi tải dữ liệu
            drawChart(model);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
        }
    }
    private void drawChart(DefaultTableModel model) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int i = 0; i < model.getRowCount(); i++) {
            String tenSach = (String) model.getValueAt(i, 1);
            int soLuongMuon = (int) model.getValueAt(i, 2);
            dataset.addValue(soLuongMuon, "Số lượng mượn", tenSach);
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê sách được mượn", // Tiêu đề biểu đồ
                "Tên sách", // Trục X
                "Số lượng", // Trục Y
                dataset // Dữ liệu
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(PanelBieuDo.getSize());
        PanelBieuDo.removeAll();
        PanelBieuDo.add(chartPanel);
        PanelBieuDo.revalidate();
        PanelBieuDo.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeSachDuocMuon = new javax.swing.JTable();
        PanelBieuDo = new javax.swing.JPanel();
        btnExportPDF = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        btnMuonQuaHan = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        btnThuTienPhat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblThongKeSachDuocMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng mượn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblThongKeSachDuocMuon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 490, 340));

        PanelBieuDo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PanelBieuDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 620, 400));

        btnExportPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnPDF.jpg"))); // NOI18N
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 100, 49, 43));

        btnDocGia.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnDocGia.setForeground(new java.awt.Color(1, 16, 156));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 70));

        btnMuonQuaHan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnMuonQuaHan.jpg"))); // NOI18N
        btnMuonQuaHan.setBorder(null);
        btnMuonQuaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonQuaHanActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonQuaHan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 134, 43));

        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnMuonTra.png"))); // NOI18N
        btnMuonTra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 15, 156), 2, true));
        btnMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 60));

        btnThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnThuTienPhat.png"))); // NOI18N
        btnThuTienPhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 156), 2));
        btnThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TKSachDcMuon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics g, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) g;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                // Vẽ tiêu đề
                String title = "Thống kê sách được mượn";
                g2d.setFont(new Font("Arial", Font.BOLD, 20));
                FontMetrics fm = g2d.getFontMetrics();
                int titleWidth = fm.stringWidth(title);
                g2d.drawString(title, (int) ((pageFormat.getWidth() - titleWidth) / 2), 50);

                // Vẽ ngày giờ hiện tại
                String currentDateTimeString = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date());
                g2d.setFont(new Font("Arial", Font.PLAIN, 12));
                g2d.drawString(currentDateTimeString, 10, 70);

                // Vẽ bảng
                int y = 100;
                g2d.setFont(new Font("Arial", Font.BOLD, 14));
                g2d.drawString("Mã sách", 50, y);
                g2d.drawString("Tên sách", 200, y);
                g2d.drawString("Số lượng mượn", 450, y);
                y += 20;

                g2d.setFont(new Font("Arial", Font.PLAIN, 12));
                for (int i = 0; i < tblThongKeSachDuocMuon.getRowCount(); i++) {
                    g2d.drawString((String) tblThongKeSachDuocMuon.getValueAt(i, 0), 50, y);
                    g2d.drawString((String) tblThongKeSachDuocMuon.getValueAt(i, 1), 200, y);
                    g2d.drawString(String.valueOf(tblThongKeSachDuocMuon.getValueAt(i, 2)), 450, y);
                    y += 20;
                }

                // Vẽ biểu đồ
                int chartY = y + 20; // Vị trí vẽ biểu đồ
                PanelBieuDo.printAll(g2d.create(0, chartY, (int) pageFormat.getWidth(), (int) pageFormat.getHeight() - chartY));

                return PAGE_EXISTS;
            }
        });

        boolean doPrint = printerJob.printDialog();
        if (doPrint) {
            try {
                printerJob.print();
            } catch (PrinterException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi in: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void btnMuonQuaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonQuaHanActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMuonQuaHanActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);

        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraActionPerformed
        // TODO add your handling code here:
        QLMuon QLM = new QLMuon();
        QLM.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMuonTraActionPerformed

    private void btnThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuTienPhatActionPerformed
        // TODO add your handling code here:
        ThuTienPhat ttp = new ThuTienPhat();
        ttp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThuTienPhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SachDuocMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SachDuocMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SachDuocMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SachDuocMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SachDuocMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBieuDo;
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnMuonQuaHan;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnThuTienPhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongKeSachDuocMuon;
    // End of variables declaration//GEN-END:variables
}
