/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import smartlibrarydb.MyConnection;

/**
 *
 * @author dangt
 */
public class ThemNV extends javax.swing.JFrame {

    /**
     * Creates new form ThemNV
     */
    private JPanel contenPanel;
    
    public ThemNV() {
        initComponents();
    }
    
    //các phương thức setter
    public void setMaNV(String MaNV){
        tfMaNV.setText(MaNV);
    }
    public void setHoTen(String HoTen){
        tfHoTen.setText(HoTen);
    }
    public void setNgaySinh(String NgaySinh){
        tfNgaySinh.setText(NgaySinh);
    }
    public void setDiaChi(String DiaChi){
        tfDiaChi.setText(DiaChi);
    }
    public void setSDT(String SDT){
        tfSDT.setText(SDT);
    }
    public void setEmail(String Email){
        tfEmail.setText(Email);
    }
    public void setNgayVaoLam(String NgayVaoLam){
        tfNgayVaoLam.setText(NgayVaoLam);
    }
    public void setMaBP(String MaBP){
        cbMaBP.setSelectedItem(MaBP);
    }
    public void setMatKhau(String MatKhau){
        tfMatKhau.setText(MatKhau);
    }
    private boolean isUpdateMode = false; // Biến để xác định chế độ

    // Phương thức để thiết lập chế độ cập nhật
    public void setUpdateMode(boolean mode) {
        this.isUpdateMode = mode;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemNV = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        tfMaNV = new javax.swing.JTextField();
        tfHoTen = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfNgaySinh = new javax.swing.JTextField();
        tfNgayVaoLam = new javax.swing.JTextField();
        tfMatKhau = new javax.swing.JPasswordField();
        cbMaBP = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThemNV.setBackground(new java.awt.Color(15, 166, 85));
        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnLuu.png"))); // NOI18N
        btnThemNV.setBorder(null);
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 700, 70, 30));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnQuayLai.jpg"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, 70, 30));

        tfMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaNVActionPerformed(evt);
            }
        });
        getContentPane().add(tfMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 300, 35));
        getContentPane().add(tfHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 300, 35));
        getContentPane().add(tfSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 300, 35));
        getContentPane().add(tfDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 300, 35));
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 300, 35));
        getContentPane().add(tfNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 300, 35));
        getContentPane().add(tfNgayVaoLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 300, 35));
        getContentPane().add(tfMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, 300, 35));

        cbMaBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BPNVTT", "BPNVTK" }));
        getContentPane().add(cbMaBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 300, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/ThemNhanVien.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearText(){
        tfMaNV.setText("");
        tfHoTen.setText("");
        tfNgaySinh.setText("");
        tfDiaChi.setText("");
        tfSDT.setText("");
        tfEmail.setText("");
        tfNgayVaoLam.setText("");
        cbMaBP.setSelectedIndex(0);
        tfMatKhau.setText("");
    }
    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        String MaNV = tfMaNV.getText();
        String HoTen = tfHoTen.getText();
        String NgaySinh = tfNgaySinh.getText();
        String DiaChi = tfDiaChi.getText();
        String SDT = tfSDT.getText();
        String Email = tfEmail.getText();
        String NgayVaoLam = tfNgayVaoLam.getText();
        String MaBP = cbMaBP.getSelectedItem().toString();
        String MatKhau = tfMatKhau.getText();

        if (MaNV.isEmpty() || HoTen.isEmpty() || NgaySinh.isEmpty() || SDT.isEmpty() || NgayVaoLam.isEmpty() || MatKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        try {
            java.util.Date ngaySinhDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgaySinh);
            java.sql.Date NgaySinhSQL = new java.sql.Date(ngaySinhDate.getTime());
            java.util.Date ngayVaoLamDate = new SimpleDateFormat("yyyy-MM-dd").parse(NgayVaoLam);
            java.sql.Date NgayVaoLamSQL = new java.sql.Date(ngayVaoLamDate.getTime());
            byte[] passwordBytes = MatKhau.getBytes(StandardCharsets.UTF_8);

            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            int result;

            if (isUpdateMode) {
                String updateQuery = "update NHANVIEN set HoTen = ?, NgaySinh = ?, DiaChi = ?, SDT = ?, Email = ?, NgayVaoLam = ?, MaBP = ?, MatKhau = ? where MaNV = ?";
                ps = con.prepareStatement(updateQuery);
                ps.setString(1, HoTen);
                ps.setDate(2, NgaySinhSQL);
                ps.setString(3, DiaChi);
                ps.setString(4, SDT);
                ps.setString(5, Email);
                ps.setDate(6, NgayVaoLamSQL);
                ps.setString(7, MaBP);
                ps.setBytes(8, passwordBytes);
                ps.setString(9, MaNV);
            } else {
                String insertQuery = "insert into NHANVIEN (MaNV, HoTen, NgaySinh, DiaChi, SDT, Email, NgayVaoLam, MatKhau, MaBP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                ps = con.prepareStatement(insertQuery);
                ps.setString(1, MaNV);
                ps.setString(2, HoTen);
                ps.setDate(3, NgaySinhSQL);
                ps.setString(4, DiaChi);
                ps.setString(5, SDT);
                ps.setString(6, Email);
                ps.setDate(7, NgayVaoLamSQL);
                ps.setBytes(8, passwordBytes);
                ps.setString(9, MaBP);
            }

            result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, isUpdateMode ? "Cập nhật thông tin nhân viên thành công!" : "Thêm nhân viên thành công!");
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, isUpdateMode ? "Cập nhật thông tin nhân viên thất bại." : "Thêm nhân viên thất bại.");
            }

            ps.close();
            con.close();
        } catch (ParseException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, (isUpdateMode ? "Cập nhật thông tin nhân viên thất bại: " : "Thêm nhân viên thất bại: ") + e.getMessage());
        }        
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        QLNhanVien qlnv = new QLNhanVien();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tfMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JComboBox<String> cbMaBP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JPasswordField tfMatKhau;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfNgayVaoLam;
    private javax.swing.JTextField tfSDT;
    // End of variables declaration//GEN-END:variables
}
