/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import Base.DSMuonQuaHan;
import Base.LapPhieuThu;
import Base.QLDocGia;
import Base.QLMuon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smartlibrarydb.MyConnection;

/**
 *
 * @author Suzi161099
 */
public class ThuTienPhat extends javax.swing.JFrame {

    /**
     * Creates new form ThuTienPhat
     */
    private DefaultTableModel tableModel;
    public ThuTienPhat() {
        initComponents();
        loadDataToTable();
    }
    
    private void loadDataToTable() {
        String query = "select * from PHIEUTHUTIENPHAT";
        ResultSet rs = MyConnection.executeQuery(query);
        
        if (rs == null) {
            // Xử lý khi không lấy được dữ liệu
            return;
        }
        
        try {
            tableModel = (DefaultTableModel) tblThuTienPhat.getModel();
            tableModel.setRowCount(0); // Xóa các hàng cũ

            while (rs.next()) {
                String MaPhieuThu = rs.getString("MaPhieuThu");
                String MaPhieu = rs.getString("MaPhieu");
                String NgayLap = rs.getString("NgayLap");
                String LyDo = rs.getString("LyDo");
                int SoTien = rs.getInt("SoTien");

                // Thêm dòng mới vào tableModel
                tableModel.addRow(new Object[]{MaPhieuThu, MaPhieu, NgayLap, LyDo, SoTien});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDocGia = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        btnLapPhieuThuTienPhat = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThuTienPhat = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDocGia.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnDocGia.setForeground(new java.awt.Color(1, 16, 156));
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnDocGia.png"))); // NOI18N
        btnDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 15, 156), 2));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 220, 70));

        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnMuonTra.png"))); // NOI18N
        btnMuonTra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 15, 156), 2, true));
        btnMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 70));

        btnLapPhieuThuTienPhat.setBackground(new java.awt.Color(15, 166, 85));
        btnLapPhieuThuTienPhat.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btnLapPhieuThuTienPhat.setForeground(new java.awt.Color(255, 255, 255));
        btnLapPhieuThuTienPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/btnLapPhieuThuTienPhat.png"))); // NOI18N
        btnLapPhieuThuTienPhat.setBorder(null);
        btnLapPhieuThuTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieuThuTienPhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapPhieuThuTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 230, 40));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/btnThongKe.jpg"))); // NOI18N
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 65));

        tblThuTienPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu thu", "Mã phiếu mượn", "Ngày lập", "Lý do", "Số tiền thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblThuTienPhat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 1160, -1));

        btnEdit.setBackground(new java.awt.Color(16, 166, 85));
        btnEdit.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 620, 120, 40));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/PhieuThuTienPhat.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapPhieuThuTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieuThuTienPhatActionPerformed
        // TODO add your handling code here:
        LapPhieuThu lpthu = new LapPhieuThu();
        lpthu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLapPhieuThuTienPhatActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        QLDocGia qldg = new QLDocGia();
        qldg.setVisible(true);

        dispose(); //dong trang mainThuThu
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraActionPerformed
        // TODO add your handling code here:
        QLMuonTra qlmuontra = new QLMuonTra();
        qlmuontra.setVisible(true);
        dispose();   
    }//GEN-LAST:event_btnMuonTraActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        DSMuonQuaHan dSMuonQuaHan = new DSMuonQuaHan();
        dSMuonQuaHan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblThuTienPhat.getSelectedRow();
        if (selectedRow != -1) { // Kiểm tra nếu có dòng nào được chọn
            // Lấy thông tin từ bảng
            String MaPhieuThu = tblThuTienPhat.getValueAt(selectedRow, 0).toString();
            String MaPhieu = tblThuTienPhat.getValueAt(selectedRow, 1).toString();
            String NgayLap = tblThuTienPhat.getValueAt(selectedRow, 2).toString();
            String LyDo = tblThuTienPhat.getValueAt(selectedRow, 3).toString();
            String SoTien = tblThuTienPhat.getValueAt(selectedRow, 4).toString();
          // Chuyển hướng sang LapPhieuThu để sửa thông tin
            LapPhieuThu lpthu = new LapPhieuThu();
            lpthu.setMaPhieuThu(MaPhieuThu);
            lpthu.setMaPhieu(MaPhieu);
            lpthu.setNgayLap(NgayLap);
            lpthu.setLyDo(LyDo);
            lpthu.setSoTien(SoTien);
            lpthu.setUpdateMode(true); // Chế độ chỉnh sửa
            lpthu.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phiếu thu cần sửa.");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblThuTienPhat.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phiếu thu cần xóa.");
            return;
        }

        String MaPhieuThu = tableModel.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa phiếu thu này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "delete from PHIEUTHUTIENPHAT where MaPhieuThu = ?";
            try (Connection con = MyConnection.getConnection();
                 PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, MaPhieuThu);
                int rowsAffected = ps.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa phiếu thu thành công.");
                    tableModel.removeRow(selectedRow);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa phiếu thu thất bại.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Xóa phiếu thu thất bại: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuTienPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuTienPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuTienPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuTienPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuTienPhat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLapPhieuThuTienPhat;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblThuTienPhat;
    // End of variables declaration//GEN-END:variables
}
